function report = hmatrixScalingManifest(rows, maxMatvecError, maxRank, maxStorageExponent)
%HMATRIXSCALINGMANIFEST Gate H-matrix accuracy and storage complexity.
arguments
    rows (:,1) struct
    maxMatvecError (1,1) double {mustBeNonnegative} = 1e-8
    maxRank (1,1) double {mustBeInteger, mustBePositive} = 20
    maxStorageExponent (1,1) double {mustBeNonnegative} = 1.25
end
if numel(rows) < 3
    error("hmatrixScalingManifest:rows", "At least three scaling rows are required.");
end

counts = [rows.pointCount];
ranks = [rows.maxRank];
lowRankBlocks = [rows.lowRankBlocks];
stored = [rows.storedEntries];
dense = [rows.denseEntries];
compression = [rows.compressionRatio];
errors = [rows.matvecRelativeError];
storageExponent = log(stored(2:end)./stored(1:end-1)) ./ ...
    log(counts(2:end)./counts(1:end-1));
denseExponent = log(dense(2:end)./dense(1:end-1)) ./ ...
    log(counts(2:end)./counts(1:end-1));
ratioError = abs(compression - stored./dense);
timings = [[rows.buildSeconds], [rows.matvecSeconds], [rows.denseReferenceSeconds]];

checks = struct( ...
    "pointCountsStrictlyIncrease", all(diff(counts) > 0), ...
    "lowRankBlocksPresent", all(lowRankBlocks > 0), ...
    "rankIsBounded", all(ranks >= 1 & ranks <= maxRank), ...
    "storedEntriesAreCompressed", all(stored > 0 & stored < dense), ...
    "compressionRatioMatchesStorage", max(ratioError) <= 1e-12, ...
    "compressionImprovesWithSize", all(diff(compression) < 0), ...
    "matvecMatchesDenseReference", all(errors <= maxMatvecError), ...
    "storedEntryGrowthIsSubquadratic", all(storageExponent <= maxStorageExponent), ...
    "denseReferenceGrowthIsQuadratic", all(denseExponent >= 1.9), ...
    "timingsAreNonnegative", all(timings >= 0));

report = struct( ...
    "schema", "matlab-acoustic-fembem.hmatrix-scaling-manifest.v1", ...
    "ok", all(structfun(@logical, checks)), ...
    "checks", checks, ...
    "pointCounts", counts, ...
    "maxRanks", ranks, ...
    "storedEntries", stored, ...
    "denseEntries", dense, ...
    "compressionRatios", compression, ...
    "maxMatvecRelativeError", max(errors), ...
    "storageGrowthExponents", storageExponent, ...
    "denseGrowthExponents", denseExponent, ...
    "maxCompressionRatioConsistencyError", max(ratioError));
end
