function model = addFirstOrderFemBemSpaces(model)
%ADDFIRSTORDERFEMBEMSPACES Fix this lane to first-order H1/HCurl/RWG spaces.

model.spaces = struct();
model.spaces.h1 = struct( ...
    "family", "Lagrange", ...
    "order", 1, ...
    "cell", "tetrahedron", ...
    "kind", "P1");
model.spaces.hcurl = struct( ...
    "family", "Nedelec", ...
    "order", 0, ...
    "cell", "tetrahedron", ...
    "kind", "Nedelec0");
model.spaces.scalarBem = struct( ...
    "family", "Lagrange", ...
    "order", 1, ...
    "cell", "triangle", ...
    "kind", "P1");
model.spaces.rwg = struct( ...
    "family", "Rao-Wilton-Glisson", ...
    "order", 0, ...
    "cell", "triangle-pair", ...
    "kind", "RWG");
model.spaces.policy = "first_order_h1_p1_hcurl_nedelec0_bem_p1_rwg_only";
end
