function model = assembleFirstOrderFemBemTrace(model)
%ASSEMBLEFIRSTORDERFEMBEMTRACE Assemble the P1/P1 FEM-BEM trace scaffold.

model = addFirstOrderFemBemSpaces(model);
model.topology = buildFirstOrderTopology(model);

nFem = size(model.lukas.geo.nodes, 1);
nBem = numel(model.trace.nodeIds);
if ~isfield(model.trace, "traceRowIdentity")
    model.trace.traceRowIdentity = localTraceRowIdentity(model.trace.nodeIds);
end
if ~isfield(model.trace, "assemblyRuleId")
    model.trace.assemblyRuleId = "first_order_tet_h1_trace_tri_p1_bem_teaching_v1";
end
if ~isfield(model.trace, "quadratureRuleId")
    model.trace.quadratureRuleId = "tri_p1_exact_mass_regular_kernel_teaching_v1";
end
if ~isfield(model.trace, "traceBasisSchemaId")
    model.trace.traceBasisSchemaId = "matlab_h1_p1_to_scalar_bem_p1_trace_basis_v1";
end
traceMatrix = sparse(1:nBem, model.trace.nodeIds, 1, nBem, nFem);
traceOutputDigest = localTraceMatrixSha256Id(traceMatrix, nBem, nFem);
model.trace.traceOutputDigest = traceOutputDigest;

model.operators = struct();
model.operators.fem = assembleLukasP1Stiffness(model, 1);
model.operators.bem = assembleGypsilabP1SurfaceMass(model);
model.operators.trace = struct( ...
    "matrix", traceMatrix, ...
    "femNodeIds", model.trace.nodeIds, ...
    "bemNodeIds", (1:nBem).', ...
    "meshId", model.trace.meshId, ...
    "surfaceMeshId", model.trace.surfaceMeshId, ...
    "traceArtifactId", model.trace.traceArtifactId, ...
    "traceOperatorArtifactId", model.trace.traceOperatorArtifactId, ...
    "traceOperatorPolicy", model.trace.traceOperatorPolicy, ...
    "traceOutputArtifactId", model.trace.traceOutputArtifactId, ...
    "traceOutputDigest", model.trace.traceOutputDigest, ...
    "traceOutputPath", model.trace.traceOutputPath, ...
    "traceObservableId", model.trace.traceObservableId, ...
    "traceObservableFamily", model.trace.traceObservableFamily, ...
    "traceBasisSchemaId", model.trace.traceBasisSchemaId, ...
    "assemblyRuleId", model.trace.assemblyRuleId, ...
    "quadratureRuleId", model.trace.quadratureRuleId, ...
    "traceRowIdentity", model.trace.traceRowIdentity, ...
    "sourceFileId", model.trace.sourceFileId, ...
    "boundaryNumbers", model.trace.boundaryNumbers, ...
    "boundaryNames", model.trace.boundaryNames, ...
    "boundaryRowIdentity", model.trace.boundaryRowIdentity, ...
    "rwgToHcurlEdgeIds", model.topology.trace.rwgToHcurlEdgeIds);
model.operators.policy = "first_order_h1_hcurl_rwg_trace_scaffold";
model.status = "operators_ready_first_order_h1_hcurl_rwg_trace";
end


function identity = localTraceRowIdentity(traceNodeIds)
%LOCALTRACEROWIDENTITY Bind trace rows to FEM/BEM node ids.

nRows = numel(traceNodeIds);
identity = struct( ...
    "trace_row_index", num2cell((1:nRows).'), ...
    "fem_node_id", num2cell(traceNodeIds(:)), ...
    "bem_node_id", num2cell(traceNodeIds(:)), ...
    "surface_node_index", num2cell((1:nRows).'));
end


function digest = localTraceMatrixSha256Id(traceMatrix, nBem, nFem)
%LOCALTRACEMATRIXSHA256ID Stable identity for the assembled trace output.

[row, col, val] = find(traceMatrix);
lines = [
    "trace_matrix_p1"
    "n_bem=" + string(nBem)
    "n_fem=" + string(nFem)
    ];
for k = 1:numel(val)
    lines(end + 1, 1) = string(row(k)) + "," + string(col(k)) + "," + sprintf("%.17g", val(k)); %#ok<AGROW>
end
payload = join(lines, newline);
md = javaMethod("getInstance", "java.security.MessageDigest", "SHA-256");
md.update(uint8(char(payload)));
hash = typecast(md.digest(), "uint8");
hex = lower(reshape(dec2hex(hash, 2).', 1, []));
digest = "sha256:" + string(hex);
end
