function tests = testMcpCapstoneSuiteTool
%TESTMCPCAPSTONESUITETOOL MCP extension and artifact-gate tests.
tests = functiontests(localfunctions);
end


function testExtensionManifest(testCase)
repoRoot = fileparts(fileparts(mfilename("fullpath")));
path = fullfile(repoRoot, "mcp", "extensions", "capstone-suite-tools.json");
manifest = jsondecode(fileread(path));
verifyEqual(testCase, string(manifest.tools.name), ...
    "acoustic_fembem_capstone_suite_artifact_gate");
verifyEqual(testCase, ...
    string(manifest.signatures.acoustic_fembem_capstone_suite_artifact_gate.function), ...
    "acoustic_fembem.check_capstone_suite_artifact_gate");
end


function testGateAcceptsSharedCapstoneSuite(testCase)
result = acoustic_fembem.capstone_suite_artifact_gate(validSummary());
verifyEqual(testCase, string(result.status), "ok");
verifyTrue(testCase, all(structfun(@logical, result.checks)));
end


function testWrapperRejectsQuitAndMissingTraceCase(testCase)
summary = validSummary();
summary.engine_quit_called = true;
summary.cases(9).passed = false;
result = jsondecode(acoustic_fembem.check_capstone_suite_artifact_gate(jsonencode(summary)));
verifyEqual(testCase, string(result.status), "needs_attention");
verifyFalse(testCase, result.checks.execution_route_attach_only);
verifyFalse(testCase, result.checks.ten_cases_passed);
end


function summary = validSummary()
cases = repmat(struct("id", "", "passed", true), 10, 1);
for idx = 1:10
    cases(idx).id = sprintf("GYP-%03d", idx + 90);
end
summary = struct( ...
    "shared_session", "MATLAB_1212", ...
    "matlab_version", "26.1.0 (R2026a)", ...
    "execution_route", "shared_matlab_engine_existing_session", ...
    "attached_only", true, ...
    "engine_quit_called", false, ...
    "shared_java_class_available_before", true, ...
    "shared_java_class_available_after", true, ...
    "source_kind", "gypsilab_native_gyp_091_100_capstone_suite", ...
    "replay_script_sha256", repmat('a', 1, 64), ...
    "source_example_ids", compose("GYP-%03d", (91:100).'), ...
    "mesh_contract", struct("format", ".vol", "surface", "tri", ...
        "volume", "tet", "field_order", "P1"), ...
    "capabilities", struct("ok", true, "ngsolve_version", "6.2", ...
        "mesh_vertices", 4, "mesh_elements", 1, "h1_dofs", 4, ...
        "hcurl_dofs", 6, "has_bem", true, "has_laplace_sl", true, ...
        "has_helmholtz_sl", true), ...
    "cases", cases, ...
    "public_gate_policy", "fem_bem_capstone_suite_gate_v1", ...
    "public_gate_status", "ok", ...
    "public_input_sha256", repmat('b', 1, 64), ...
    "json_sidecar_used", true, ...
    "run_date_utc", "2026-07-12T00:00:00Z", ...
    "timing", struct("total_s", 0.5, "ngsolve_capability_query_s", 0.3));
end
