function tests = testMcpDuctBandGapTool
%TESTMCPDUCTBANDGAPTOOL MCP extension and artifact tests.
tests = functiontests(localfunctions);
end


function testExtensionManifest(testCase)
root = fileparts(fileparts(mfilename("fullpath")));
manifest = jsondecode(fileread(fullfile(root, "mcp", "extensions", ...
    "duct-band-gap-tools.json")));
verifyEqual(testCase, string(manifest.tools.name), ...
    "acoustic_fembem_duct_band_gap_artifact_gate");
verifyEqual(testCase, ...
    string(manifest.signatures.acoustic_fembem_duct_band_gap_artifact_gate.function), ...
    "acoustic_fembem_check_duct_band_gap_artifact_gate");
end


function testGateAcceptsSharedDuctAndFreeSpaceEvidence(testCase)
result = acoustic_fembem.duct_band_gap_artifact_gate(validSummary());
verifyEqual(testCase, string(result.status), "ok");
verifyTrue(testCase, all(structfun(@logical, result.checks)));
end


function testWrapperRejectsMissingConfinementEvidence(testCase)
summary = validSummary();
summary.source_contract.regenerated = false;
summary.free_space_control.insertion_loss_spread_db = 5.0;
summary.public_gate.status = "needs_attention";
result = jsondecode(acoustic_fembem.check_duct_band_gap_artifact_gate(jsonencode(summary)));
verifyEqual(testCase, string(result.status), "needs_attention");
verifyFalse(testCase, result.checks.fresh_ngsolve_reference_was_generated);
verifyFalse(testCase, result.checks.free_space_control_is_numeric_and_featureless);
verifyFalse(testCase, result.checks.public_confinement_gate_passed);
end


function summary = validSummary()
summary = struct( ...
    "shared_session","MATLAB_1212", ...
    "matlab_version","26.1.0 (R2026a)", ...
    "execution_route","shared_matlab_engine_existing_session", ...
    "attached_only",true, "engine_quit_called",false, ...
    "shared_java_bridge_available_before",true, ...
    "shared_java_bridge_available_after",true, ...
    "matlab_process_ids_before",[1212,12428], ...
    "matlab_process_ids_after",[1212,12428], ...
    "source_contract",struct( ...
        "kind","repository_native_duct_bloch_and_free_space_chain", ...
        "generator_sha256",repmat('a',1,64), ...
        "fresh_reference_sha256",repmat('b',1,64), ...
        "chain_vol_sha256",repmat('c',1,64), ...
        "regenerated",true, "ngsolve_version","6.2", ...
        "bloch_point_count",9, "frequency_point_count",18, ...
        "loaded_duct_ndof",29998), ...
    "test_evidence",struct("duct_passed",3,"duct_failed",0, ...
        "chain_passed",4,"chain_failed",0), ...
    "free_space_control",struct("pass",true, ...
        "wavenumbers",[0.6,1.4,2.2,3.0], ...
        "insertion_loss_spread_db",0.47, ...
        "maximum_insertion_loss_db",3.94), ...
    "public_gate",struct("policy","acoustic_duct_band_gap_gate_v1", ...
        "status","ok"), ...
    "json_sidecars_used",true, "run_date_utc","2026-07-13T00:00:00Z", ...
    "timing_breakdown_s",struct("reference_generation",23.0, ...
        "shared_matlab_duct_and_chain_tests",83.0, ...
        "free_space_numeric_control",22.0, "mcp_verification",1.0));
end
