function tests = testMcpRwgHcurlTraceTool
%TESTMCPRWGHCURLTRACETOOL MCP extension and artifact-gate tests.
tests = functiontests(localfunctions);
end


function testExtensionManifest(testCase)
repoRoot = fileparts(fileparts(mfilename("fullpath")));
path = fullfile(repoRoot, "mcp", "extensions", "rwg-hcurl-trace-tools.json");
manifest = jsondecode(fileread(path));
verifyEqual(testCase, string(manifest.tools.name), ...
    "acoustic_fembem_rwg_hcurl_trace_artifact_gate");
verifyEqual(testCase, ...
    string(manifest.signatures.acoustic_fembem_rwg_hcurl_trace_artifact_gate.function), ...
    "acoustic_fembem_check_rwg_hcurl_trace_artifact_gate");
end


function testGateAcceptsSharedTraceSuite(testCase)
result = acoustic_fembem.rwg_hcurl_trace_artifact_gate(validSummary());
verifyEqual(testCase, string(result.status), "ok");
verifyTrue(testCase, all(structfun(@logical, result.checks)));
end


function testWrapperRejectsQuitAndFalseMaxwellClaim(testCase)
summary = validSummary();
summary.engine_quit_called = true;
summary.maxwell_bem_claimed = true;
summary.cases(10).passed = false;
result = jsondecode(acoustic_fembem.check_rwg_hcurl_trace_artifact_gate(jsonencode(summary)));
verifyEqual(testCase, string(result.status), "needs_attention");
verifyFalse(testCase, result.checks.execution_route_attach_only);
verifyFalse(testCase, result.checks.maxwell_bem_not_overclaimed);
verifyFalse(testCase, result.checks.ten_source_cases_passed);
end


function summary = validSummary()
cases = repmat(struct("id", "", "passed", true), 10, 1);
for idx = 1:10
    cases(idx).id = sprintf("GYP-%03d", idx + 80);
end
summary = struct( ...
    "shared_session", "MATLAB_1212", ...
    "matlab_version", "26.1.0 (R2026a)", ...
    "execution_route", "shared_matlab_engine_existing_session", ...
    "attached_only", true, ...
    "engine_quit_called", false, ...
    "shared_java_bridge_available_before", true, ...
    "shared_java_bridge_available_after", true, ...
    "mcp_runtime", struct("server_version", "0.11.2", ...
        "session_mode", "auto", "display_mode", "nodesktop", ...
        "preflight_single_shared_session", true, ...
        "preflight_shared_session", "MATLAB_1212", ...
        "attached_existing", true, "capture_feval_passed", true, ...
        "desktop_eval_failure_reproduced", true, ...
        "matlab_process_ids_before", [1212, 12428], ...
        "matlab_process_ids_after", [1212, 12428]), ...
    "source_kind", "gypsilab_native_gyp_081_090_rwg_hcurl_suite", ...
    "replay_script_sha256", repmat('a', 1, 64), ...
    "source_example_ids", compose("GYP-%03d", (81:90).'), ...
    "mesh_contract", struct("format", ".vol", "surface", "tri", ...
        "volume", "tet", "field_order", "P1", ...
        "volume_edge_space", "Nedelec0", "boundary_vector_space", "RWG0"), ...
    "capabilities", struct("ok", true, "ngsolve_version", "6.2", ...
        "hcurl_dofs", 6, "has_maxwell_sl", false), ...
    "maxwell_bem_claimed", false, ...
    "cases", cases, ...
    "trace_diagnostics", struct("rwg_dofs", 6, "hcurl_dofs", 6, ...
        "selector_nonzeros", 6, "rotated_trace_nonzeros", 6, ...
        "rotated_trace_rank", 6), ...
    "matlab_tests", struct("test_count", 18, "passed", 18, ...
        "failed", 0, "incomplete", 0), ...
    "public_gate", struct("policy", "rwg_hcurl_trace_consistency_gate_v1", ...
        "status", "ok", "solver_ready", true), ...
    "public_input_sha256", repmat('b', 1, 64), ...
    "json_sidecar_used", true, ...
    "run_date_utc", "2026-07-12T00:00:00Z", ...
    "timing", struct("total_s", 6.0, "ngsolve_capability_query_s", 0.4, ...
        "trace_diagnostics_s", 0.01, "matlab_tests_s", 5.0));
end
