function tests = testDuctBandGap
%TESTDUCTBANDGAP Stage 9: sonic-crystal band gap in a rigid duct (locked).
%
% Locks the NGSolve FEM reference (committed
% validation/data/ngsolve_duct_band_reference.mat, regenerated by
% validation/exportNgsolveDuctBandReference.py): Bloch band structure of
% the duct unit cell (a = 1.0, d = 1.5, sound-soft sphere R = 0.3 - the
% SAME scatterer family as the stage-8 free-space chain) plus the
% transmission through the finite 5-cell crystal with one-way ports.
%
% The physics this locks (2026-07-04 measurements): confinement creates
% what free space could not - the transmission shows the full
% stop / pass / stop structure aligned with the Bloch bands:
%   k <= 2.2            below band 1 (Dirichlet inclusions cut off the
%                       long-wavelength plane mode): T ~ 1e-4
%   band 1 [2.31, 2.52] passband: T up to 0.27 (finite 5-cell crystal)
%   gap [2.52, 3.65]    Bragg-type gap: T ~ 1e-3 within the single-mode
%                       window (sweep tops at 2.9 < pi = transverse cutoff)
% Gates: empty-lattice Bloch bands match the analytic duct dispersion to
% 2e-4; the EMPTY duct is transparent to 1e-3 (port exactness).

tests = functiontests(localfunctions);
end


function setupOnce(~)
repoRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(repoRoot, "matlab_api")));
end


function S = loadReference()
repoRoot = fileparts(fileparts(mfilename("fullpath")));
matFile = fullfile(repoRoot, "validation", "data", ...
    "ngsolve_duct_band_reference.mat");
if ~isfile(matFile)
    error("testDuctBandGap:reference", ...
        "Missing %s - regenerate with python validation/exportNgsolveDuctBandReference.py", ...
        matFile);
end
S = load(matFile);
end


function testEmptyLatticeGateAndPortTransparency(testCase)
S = loadReference();
verifyLessThan(testCase, S.emptyLatticeMaxRelErr, 1e-3);   % measured 2.0e-4
verifyLessThan(testCase, max(abs(S.transmissionEmpty - 1)), 1e-2);
end


function testBlochGapExists(testCase)
S = loadReference();
verifyGreaterThan(testCase, S.gapHigh - S.gapLow, 1.0);    % measured 1.13
verifyEqual(testCase, S.gapLow, 2.519, "AbsTol", 0.1);     % golden band
verifyEqual(testCase, S.gapHigh, 3.647, "AbsTol", 0.15);
% band 1 rises from 2.31 (q=0) to the zone edge - the soft inclusions
% also cut off the long-wavelength plane mode below the band
verifyEqual(testCase, min(S.bands(:, 1)), 2.314, "AbsTol", 0.1);
end


function testTransmissionAlignsWithBands(testCase)
S = loadReference();
k = S.k(:);
T = S.transmission(:);
inPass = k >= min(S.bands(:, 1)) & k <= S.gapLow;
inGap = k > S.gapLow + 0.05;
belowBand = k <= min(S.bands(:, 1)) - 0.1;
verifyGreaterThan(testCase, max(T(inPass)), 0.1);          % measured 0.267
verifyLessThan(testCase, max(T(inGap)), 0.01);             % measured 1.9e-3
verifyLessThan(testCase, max(T(belowBand)), 0.01);         % measured 3e-4
verifyGreaterThan(testCase, max(T(inPass)) / max(T(inGap)), 50);  % 140 meas.
end
