function tests = testMcpEnergyBudgetTraceTool
%TESTMCPENERGYBUDGETTRACETOOL MCP extension and artifact-gate tests.
tests = functiontests(localfunctions);
end


function testExtensionManifest(testCase)
repoRoot = fileparts(fileparts(mfilename("fullpath")));
path = fullfile(repoRoot, "mcp", "extensions", "energy-budget-trace-tools.json");
manifest = jsondecode(fileread(path));
verifyEqual(testCase, string(manifest.tools.name), ...
    "acoustic_fembem_energy_budget_trace_artifact_gate");
verifyEqual(testCase, ...
    string(manifest.signatures.acoustic_fembem_energy_budget_trace_artifact_gate.function), ...
    "acoustic_fembem.check_energy_budget_trace_artifact_gate");
end


function testGateAcceptsSharedSessionTripleCheck(testCase)
result = acoustic_fembem.energy_budget_trace_artifact_gate(validSummary());
verifyEqual(testCase, string(result.status), "ok");
verifyTrue(testCase, all(structfun(@logical, result.checks)));
end


function testWrapperRejectsBatchQuitAndUnclassifiedPdePreflight(testCase)
summary = validSummary();
summary.engine_quit_called = true;
summary.pde_geometry_preflight = "license_only";
result = jsondecode(acoustic_fembem.check_energy_budget_trace_artifact_gate( ...
    jsonencode(summary)));
verifyEqual(testCase, string(result.status), "needs_attention");
verifyFalse(testCase, result.checks.execution_route_attach_only);
verifyFalse(testCase, result.checks.pde_preflight_classified);
end


function summary = validSummary()
summary = struct( ...
    "shared_session", "MATLAB_1212", ...
    "matlab_version", "26.1.0 (R2026a)", ...
    "execution_route", "shared_matlab_engine_existing_session", ...
    "attached_only", true, ...
    "engine_quit_called", false, ...
    "optimization_toolbox_license", true, ...
    "fmincon_path", fullfile(matlabroot, ...
        "toolbox", "shared", "optimlib", "fmincon.m"), ...
    "pde_geometry_preflight", "license_present_function_absent", ...
    "geometry_pivot_reason", ...
        "multicylinder was unavailable, so the replay used a generated local tri/tet .vol fixture.", ...
    "source_kind", "local_gypsilab_vol_fembem_optimization_example", ...
    "replay_script_sha256", repmat('a', 1, 64), ...
    "vol_artifact_policy", "generated_temp_not_git_managed", ...
    "random_seed", 647, ...
    "mesh", struct( ...
        "source_file_id", "sha256:" + string(repmat('b', 1, 64)), ...
        "volume_element", "tet4", "boundary_element", "tri3", ...
        "volume_basis", "H1_P1", "trace_basis", "scalar_P1", ...
        "points", 216, "h1_dofs", 216, "trace_dofs", 152, ...
        "trace_policy", "one_hot_boundary_node_injection_from_vol_node_ids", ...
        "basis_schema", "matlab_h1_p1_to_scalar_bem_p1_trace_basis_v1"), ...
    "objective", "0.5*norm(T*u-g)^2", ...
    "constraint", "0.5*u'*Q*u<=energy_budget", ...
    "energy_operator", "H1_P1_stiffness_plus_0.05_mass", ...
    "method_ids", ["analytic_kkt", "fmincon_sqp", "fmincon_interior_point"], ...
    "public_gate_policy", "energy_budgeted_trace_kkt_gate_v1", ...
    "public_gate_status", "ok", ...
    "public_input_sha256", repmat('c', 1, 64), ...
    "json_sidecar_used", true, ...
    "run_date_utc", "2026-07-12T00:00:00Z", ...
    "elapsed_s", 2.0);
end
