function tests = testMcpLsqnonlinMultistartTool
%TESTMCPLSQNONLINMULTISTARTTOOL MCP extension and gate tests.
tests = functiontests(localfunctions);
end


function testExtensionManifest(testCase)
repoRoot = fileparts(fileparts(mfilename("fullpath")));
path = fullfile(repoRoot, "mcp", "extensions", "lsqnonlin-multistart-tools.json");
manifest = jsondecode(fileread(path));
verifyEqual(testCase, string(manifest.tools.name), ...
    "acoustic_fembem_lsqnonlin_multistart_artifact_gate");
verifyEqual(testCase, ...
    string(manifest.signatures.acoustic_fembem_lsqnonlin_multistart_artifact_gate.function), ...
    "acoustic_fembem.check_lsqnonlin_multistart_artifact_gate");
end


function testGateAcceptsSharedSessionAudit(testCase)
result = acoustic_fembem.lsqnonlin_multistart_artifact_gate(validSummary());
verifyEqual(testCase, string(result.status), "ok");
verifyTrue(testCase, result.checks.shared_solver_session_survived);
verifyTrue(testCase, result.checks.sparse_jacobian_json_contract);
verifyTrue(testCase, result.checks.attach_only_contract);
end


function testWrapperRejectsQuitAndBadJacobian(testCase)
summary = validSummary();
summary.engine_quit_called = true;
summary.max_solver_jacobian_relative_error = 1e-2;
result = jsondecode(acoustic_fembem.check_lsqnonlin_multistart_artifact_gate( ...
    jsonencode(summary)));
verifyEqual(testCase, string(result.status), "needs_attention");
verifyFalse(testCase, result.checks.attach_only_contract);
verifyFalse(testCase, result.checks.solver_jacobian_gate_passed);
end


function summary = validSummary()
summary = struct( ...
    "shared_session", "MATLAB_1212", ...
    "matlab_version", "R2026a", ...
    "shared_solver_connected_before", true, ...
    "shared_solver_connected_after", true, ...
    "source_kind", "source_native_matlab_optimization_example", ...
    "source_digests", struct("main_m", repmat('a',1,64), ...
        "CF_m", repmat('b',1,64)), ...
    "source_copy_preserved", true, ...
    "optimization_toolbox_license", true, ...
    "lsqnonlin_path", fullfile(matlabroot, ...
        "toolbox", "shared", "optimlib", "lsqnonlin.m"), ...
    "legacy_start_rule", "x=x.*(1+10*rand(size(x)))", ...
    "legacy_start_count", 8, ...
    "legacy_all_zero", true, ...
    "corrected_start_rule", "independent_seeded_starts", ...
    "corrected_start_count", 8, ...
    "corrected_starts_distinct", true, ...
    "max_residual_norm", 5e-12, ...
    "residual_norm_tolerance", 1e-8, ...
    "max_projected_gradient_inf_norm", 6e-12, ...
    "projected_gradient_tolerance", 1e-8, ...
    "max_solver_jacobian_relative_error", 7e-9, ...
    "solver_jacobian_tolerance", 1e-5, ...
    "max_finite_difference_jacobian_relative_error", 8e-12, ...
    "finite_difference_jacobian_tolerance", 1e-7, ...
    "sparse_jacobian_converted_to_full_before_jsonencode", true, ...
    "python_engine_nargout", 0, ...
    "json_sidecar_used", true, ...
    "attached_only", true, ...
    "engine_quit_called", false, ...
    "engine_connection_released_without_quit", true, ...
    "public_gate_schema", "radia-topology-nonlinear-lsq-multistart/v1", ...
    "public_gate_status", "ok", ...
    "public_input_sha256", repmat('c',1,64), ...
    "run_date_utc", "2026-07-12T00:00:00Z");
end
