function tests = testMcpCqRefinementTool
%TESTMCPCQREFINEMENTTOOL MCP extension and artifact tests.
tests = functiontests(localfunctions);
end


function testExtensionManifest(testCase)
root = fileparts(fileparts(mfilename("fullpath")));
manifest = jsondecode(fileread(fullfile(root, "mcp", "extensions", ...
    "cq-refinement-tools.json")));
verifyEqual(testCase, string(manifest.tools.name), ...
    "acoustic_fembem_cq_refinement_artifact_gate");
verifyEqual(testCase, ...
    string(manifest.signatures.acoustic_fembem_cq_refinement_artifact_gate.function), ...
    "acoustic_fembem_check_cq_refinement_artifact_gate");
end


function testGateAcceptsTrustedWindowRefinement(testCase)
result = acoustic_fembem.cq_refinement_artifact_gate(validSummary());
verifyEqual(testCase, string(result.status), "ok");
verifyTrue(testCase, all(structfun(@logical, result.checks)));
end


function testWrapperRejectsFullWindowOverclaim(testCase)
summary = validSummary();
summary.comparison.trusted_window_fraction = 1.0;
summary.public_gate.status = "needs_attention";
result = jsondecode(acoustic_fembem.check_cq_refinement_artifact_gate(jsonencode(summary)));
verifyEqual(testCase, string(result.status), "needs_attention");
verifyFalse(testCase, result.checks.trusted_window_refinement_recorded);
verifyFalse(testCase, result.checks.public_cq_refinement_gate_passed);
end


function summary = validSummary()
run = struct("name","", "status","ok", "num_interior_only_nodes",1, ...
    "checks",struct("p1_volume_fem",true,"p1_boundary_bem",true, ...
    "johnson_nedelec_calderon_form",true,"double_layer_k_included",true));
names = ["bdf1_coarse","bdf2_coarse","bdf2_medium", ...
    "bdf2_fine","bdf2_medium_replay"];
runs = repmat(run, 1, numel(names));
for index = 1:numel(names), runs(index).name = names(index); end
summary = struct( ...
    "shared_session","MATLAB_1212", ...
    "matlab_version","26.1.0 (R2026a)", ...
    "execution_route","shared_matlab_engine_existing_session", ...
    "attached_only",true, "engine_quit_called",false, ...
    "shared_java_bridge_available_before",true, ...
    "shared_java_bridge_available_after",true, ...
    "matlab_process_ids_before",[1212,12428], ...
    "matlab_process_ids_after",[1212,12428], ...
    "matlab_path_restored",true, ...
    "source_kind","repository_native_p1_vol_fem_bem_cq_example", ...
    "vol_sha256",repmat('a',1,64), ...
    "model_contract",struct("volume_element","P1 tetrahedron", ...
    "boundary_element","P1 triangle","coupling","JohnsonNedelecCalderon", ...
    "time_method_family","Lubich CQ","absorbing_boundary","none"), ...
    "runs",runs, ...
    "comparison",struct("trusted_window_fraction",0.75, ...
    "bdf2_refinement_error_ratio",0.77, ...
    "bdf2_coarse_to_fine_relative_error",0.87, ...
    "bdf1_coarse_to_bdf2_fine_relative_error",1.05, ...
    "bdf2_medium_replay_relative_error",0.0, ...
    "contour_alias_target",1e-4, ...
    "initial_exterior_relative_amplitude",3.7e-4), ...
    "symbol_crosscheck",struct("pass",true, ...
    "maximum_symbol_relative_error",3e-16, ...
    "checks",struct("all_laplace_nodes_in_open_right_half_plane",true, ...
    "contour_alias_target_is_1e_4",true)), ...
    "public_gate",struct("policy","coupled_cq_refinement_gate_v1","status","ok"), ...
    "json_sidecars_used",true, "run_date_utc","2026-07-13T00:00:00Z", ...
    "timing_breakdown_s",struct("mesh_and_source_contract",0.1, ...
    "coupled_cq_laplace_solves",0.3, "refinement_and_replay_comparison",0.1, ...
    "result_serialization",0.1));
end
