function tests = testMcpPeriodicPmMachineTool
%TESTMCPPERIODICPMMACHINETOOL MCP extension and artifact tests.
tests = functiontests(localfunctions);
end


function testExtensionManifest(testCase)
root = fileparts(fileparts(mfilename("fullpath")));
manifest = jsondecode(fileread(fullfile(root, "mcp", "extensions", ...
    "periodic-pm-machine-tools.json")));
verifyEqual(testCase, string(manifest.tools.name), ...
    "acoustic_fembem_periodic_pm_machine_artifact_gate");
verifyEqual(testCase, ...
    string(manifest.signatures.acoustic_fembem_periodic_pm_machine_artifact_gate.function), ...
    "acoustic_fembem_check_periodic_pm_machine_artifact_gate");
end


function testGateAcceptsTopologyAwareReplay(testCase)
result = acoustic_fembem.periodic_pm_machine_artifact_gate(validSummary());
verifyEqual(testCase, string(result.status), "ok");
verifyTrue(testCase, all(structfun(@logical, result.checks)));
end


function testWrapperRejectsOnePolePromotion(testCase)
summary = validSummary();
summary.symmetry_diagnostic.rejection_recorded = false;
summary.symmetry_diagnostic.accepted_shift = "one_pole_pitch";
summary.public_gate.status = "needs_attention";
result = jsondecode(acoustic_fembem.check_periodic_pm_machine_artifact_gate(jsonencode(summary)));
verifyEqual(testCase, string(result.status), "needs_attention");
verifyFalse(testCase, result.checks.one_pole_claim_explicitly_rejected);
verifyFalse(testCase, result.checks.half_turn_symmetry_promoted);
verifyFalse(testCase, result.checks.public_periodicity_gate_passed);
end


function summary = validSummary()
run = struct("pass", true, "node_count", 10600, "element_count", 20800, ...
    "energy_j", 21.78, "coenergy_j", 22.36);
summary = struct( ...
    "shared_session", "MATLAB_1212", ...
    "matlab_version", "26.1.0 (R2026a)", ...
    "execution_route", "shared_matlab_engine_existing_session", ...
    "attached_only", true, ...
    "engine_quit_called", false, ...
    "shared_java_bridge_available_before", true, ...
    "shared_java_bridge_available_after", true, ...
    "matlab_process_ids_before", [1212, 12428], ...
    "matlab_process_ids_after", [1212, 12428], ...
    "source_kind", "source_native_unwrapped_pm_machine_example", ...
    "source_sha256", repmat('a', 1, 64), ...
    "migration", struct("hardcoded_path_replaced", true, ...
        "gui_call_suppressed", true, "function_workspace_isolation", true, ...
        "geometry_changed", false, "materials_changed", false, ...
        "boundary_conditions_changed", false), ...
    "model", struct("slot_count", 12, "pole_count", 10, ...
        "mesh_element_type", "TL3", "periodic_master_count", 33, ...
        "periodic_slave_count", 33), ...
    "symmetry_diagnostic", struct("rejected_shift", "one_pole_pitch", ...
        "one_pole_relative_error", 0.14, "one_pole_tolerance", 0.10, ...
        "rejection_recorded", true, "accepted_shift", "half_circumference", ...
        "half_turn_relative_error", 0.045, "half_turn_tolerance", 0.05), ...
    "runs", [run, run], ...
    "replay_checks", struct("energy_reproducible", true, ...
        "coenergy_reproducible", true, "airgap_rms_reproducible", true, ...
        "airgap_mean_reproducible", true, "mesh_cardinality_same_scale", true), ...
    "public_gate", struct("policy", "periodic_unwrapped_pm_machine_replay_gate_v1", ...
        "status", "ok"), ...
    "public_input_sha256", repmat('b', 1, 64), ...
    "json_sidecars_used", true, ...
    "run_date_utc", "2026-07-13T00:00:00Z", ...
    "timing_breakdown_s", struct("geometry_and_mesh", 0.5, ...
        "solver_setup", 0.1, "nonlinear_solve", 0.8, ...
        "postprocess_and_invariants", 0.1));
end
