function tests = testEducationalMeshImportQuality
%TESTEDUCATIONALMESHIMPORTQUALITY Tests for mesh import quality manifests.

tests = functiontests(localfunctions);
end


function testFirstOrderTriTetManifestPasses(testCase)
report = educationalMeshImportQualityManifest(["triangle" "tri3"], ["tetrahedron" "tet4"], ...
    "Source", "Coreform/Gmsh teaching export", ...
    "Format", ".vol", ...
    "Order", 1, ...
    "MinScaledJacobianBefore", 0.36, ...
    "MinScaledJacobianAfter", 0.75, ...
    "MinScaledJacobianThreshold", 0.2, ...
    "NegativeJacobianCountBefore", 2, ...
    "NegativeJacobianCountAfter", 0, ...
    "CadConnectivityRecorded", true, ...
    "CadComplianceRecorded", true, ...
    "BoundaryConformityTolerance", 1e-6, ...
    "MaxBoundaryDistance", 4e-7);

verifyEqual(testCase, report.kind, "educational_mesh_import_quality_manifest");
verifyEqual(testCase, report.policy, "readable_mesh_import_manifest_first_order_tri_tet_only");
verifyEqual(testCase, report.status, "ok");
verifyTrue(testCase, report.pass);
verifyTrue(testCase, report.checks.matlabVolParserPolicyHonored);
verifyTrue(testCase, report.checks.boundaryConformityWithinTolerance);
verifyEqual(testCase, report.surfaceElementTypes, ["tri"; "tri"]);
verifyEqual(testCase, report.volumeElementTypes, ["tet"; "tet"]);
verifyEqual(testCase, report.minScaledJacobianImprovement, 0.39, "AbsTol", 1e-14);
end


function testRejectsHighOrderForMatlabVolLane(testCase)
report = educationalMeshImportQualityManifest("tri", "tet", ...
    "Order", 4, ...
    "MinScaledJacobianAfter", 0.82, ...
    "NegativeJacobianCountAfter", 0);

verifyEqual(testCase, report.status, "needs_attention");
verifyFalse(testCase, report.checks.firstOrderOnly);
verifyFalse(testCase, report.checks.matlabVolParserPolicyHonored);
verifyTrue(testCase, any(report.issues == "firstOrderOnly"));
end


function testRejectsQuadHexOrMissingCadContract(testCase)
report = educationalMeshImportQualityManifest(["tri" "quad"], ["tet" "hex"], ...
    "Order", 1, ...
    "MinScaledJacobianAfter", 0.05, ...
    "MinScaledJacobianThreshold", 0.1, ...
    "NegativeJacobianCountBefore", 0, ...
    "NegativeJacobianCountAfter", 1, ...
    "CadConnectivityRecorded", false, ...
    "CadComplianceRecorded", false, ...
    "BoundaryConformityTolerance", 1e-8, ...
    "MaxBoundaryDistance", 1e-5);

verifyEqual(testCase, report.status, "needs_attention");
verifyFalse(testCase, report.checks.surfaceTrianglesOnly);
verifyFalse(testCase, report.checks.volumeTetrahedraOnly);
verifyFalse(testCase, report.checks.noNegativeJacobianAfter);
verifyFalse(testCase, report.checks.minScaledJacobianAboveThreshold);
verifyFalse(testCase, report.checks.cadConnectivityRecorded);
verifyFalse(testCase, report.checks.cadComplianceRecorded);
verifyFalse(testCase, report.checks.boundaryConformityWithinTolerance);
verifyTrue(testCase, any(report.issues == "matlabVolParserPolicyHonored"));
end
