function tests = testMcpLinearMagnetTool
%TESTMCPLINEARMAGNETTOOL MCP extension and source-artifact tests.
tests = functiontests(localfunctions);
end


function testExtensionManifest(testCase)
repoRoot = fileparts(fileparts(mfilename("fullpath")));
path = fullfile(repoRoot, "mcp", "extensions", "linear-magnet-scaling-tools.json");
manifest = jsondecode(fileread(path));
verifyEqual(testCase, string(manifest.tools.name), ...
    "acoustic_fembem_linear_magnet_artifact_gate");
verifyEqual(testCase, ...
    string(manifest.signatures.acoustic_fembem_linear_magnet_artifact_gate.function), ...
    "acoustic_fembem_check_linear_magnet_artifact_gate");
end


function testGateAcceptsSharedLinearMagnetReplay(testCase)
result = acoustic_fembem.linear_magnet_artifact_gate(validSummary());
verifyEqual(testCase, string(result.status), "ok");
verifyTrue(testCase, all(structfun(@logical, result.checks)));
end


function testWrapperRejectsRemeshedGuiReplay(testCase)
summary = validSummary();
summary.migration.geometry_changed = true;
summary.mcp_runtime.matlab_process_ids_after = [1212, 12428, 13000];
summary.public_gate.status = "needs_attention";
result = jsondecode(acoustic_fembem.check_linear_magnet_artifact_gate(jsonencode(summary)));
verifyEqual(testCase, string(result.status), "needs_attention");
verifyFalse(testCase, result.checks.migration_is_path_and_ui_only);
verifyFalse(testCase, result.checks.shared_process_set_preserved);
verifyFalse(testCase, result.checks.public_scaling_gate_passed);
end


function summary = validSummary()
summary = struct( ...
    "shared_session", "MATLAB_1212", ...
    "matlab_version", "26.1.0 (R2026a)", ...
    "execution_route", "shared_matlab_engine_existing_session", ...
    "attached_only", true, ...
    "engine_quit_called", false, ...
    "shared_java_bridge_available_before", true, ...
    "shared_java_bridge_available_after", true, ...
    "mcp_runtime", struct("server_version", "0.11.2", ...
        "session_mode", "auto", "display_mode", "nodesktop", ...
        "preflight_single_shared_session", true, ...
        "preflight_shared_session", "MATLAB_1212", ...
        "attached_existing", true, "capture_feval_passed", true, ...
        "matlab_process_ids_before", [1212, 12428], ...
        "matlab_process_ids_after", [1212, 12428]), ...
    "source_kind", "source_native_matlab_magnet_example", ...
    "source_sha256", repmat('a', 1, 64), ...
    "migration", struct("hardcoded_path_replaced", true, ...
        "gui_call_suppressed", true, "geometry_changed", false, ...
        "materials_changed", false, "boundary_conditions_changed", false), ...
    "mesh", struct("element_type", "TL3", "node_count", 1211, ...
        "element_count", 2352, "boundary_node_count", 68), ...
    "scale_factors", [1, 0.5], ...
    "public_gate", struct("policy", "linear_magnetization_scaling_gate_v1", ...
        "status", "ok"), ...
    "public_input_sha256", repmat('b', 1, 64), ...
    "live_checks", struct("a_scales_linearly", true, ...
        "b_scales_linearly", true, "energy_scales_quadratically", true, ...
        "coenergy_scales_quadratically", true), ...
    "json_sidecar_used", true, ...
    "run_date_utc", "2026-07-12T15:00:00Z", ...
    "timing", struct("geometry_setup_s", 0.2, "mesh_generation_s", 0.6, ...
        "full_scale_solve_s", 0.1, "half_scale_solve_s", 0.02));
end
