function tests = testMcpSimplexStationarityTool
%TESTMCPSIMPLEXSTATIONARITYTOOL MCP extension and gate tests.
tests = functiontests(localfunctions);
end


function testExtensionManifest(testCase)
repoRoot = fileparts(fileparts(mfilename("fullpath")));
path = fullfile(repoRoot, "mcp", "extensions", "simplex-stationarity-tools.json");
manifest = jsondecode(fileread(path));
verifyEqual(testCase, string(manifest.tools.name), ...
    "acoustic_fembem_simplex_stationarity_artifact_gate");
verifyEqual(testCase, ...
    string(manifest.signatures.acoustic_fembem_simplex_stationarity_artifact_gate.function), ...
    "acoustic_fembem.check_simplex_stationarity_artifact_gate");
end


function testGateAcceptsSharedSessionAudit(testCase)
result = acoustic_fembem.simplex_stationarity_artifact_gate(validSummary());
verifyEqual(testCase, string(result.status), "ok");
verifyTrue(testCase, result.checks.false_convergence_detected);
verifyTrue(testCase, result.checks.independent_control_accepted);
end


function testWrapperRejectsLostSessionAndControl(testCase)
summary = validSummary();
summary.shared_solver_available_after = false;
summary.public_independent_control_accepted = false;
result = jsondecode(acoustic_fembem.check_simplex_stationarity_artifact_gate(jsonencode(summary)));
verifyEqual(testCase, string(result.status), "needs_attention");
verifyFalse(testCase, result.checks.shared_solver_session_survived);
verifyFalse(testCase, result.checks.independent_control_accepted);
end


function summary = validSummary()
summary = struct( ...
    "shared_session", "MATLAB_1212", ...
    "matlab_version", "R2026a", ...
    "shared_solver_available_before", true, ...
    "shared_solver_available_after", true, ...
    "source_kind", "source_native_matlab_optimization_example", ...
    "source_digests", struct("algorithm", repmat('a',1,64), ...
        "objective", repmat('b',1,64), "example", repmat('c',1,64)), ...
    "source_copy_preserved", true, ...
    "solve_s", 0.2, ...
    "finite_difference_step", 1e-8, ...
    "method_ids", ["pathological_initial_simplex", "independent_control"], ...
    "public_gate_status", "ok", ...
    "public_false_convergence_detected", true, ...
    "public_independent_control_accepted", true, ...
    "run_date_utc", "2026-07-12T00:00:00Z");
end
