function report = a3c_async_gate(seed)
%A3C_ASYNC_GATE Teach safe asynchronous actor-critic promotion for CAE.
% Workers may finish out of order.  A gradient is accepted only when its
% behavior policy is on-policy and its captured parameter version is not
% too stale.  Accepted policy candidates still require a forward replay.
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 233
end
rng(seed,"twister");

A=[1 .2;-.3 .8;.5 -.4];             % Pa/mm teaching forward operator
theta0=[.1;-.1]; targetTheta=[.7;-.4];
yTarget=A*targetTheta;
globalVersion0=10; maxStaleness=2; workerStep=.04;
capturedVersion=[10 9 9 6];
policyVersion=[10 9 9 6];
behaviorVersion=[10 9 8 6];          % worker 3 is explicitly off-policy
queueOrder=[1 3 4 2];                % deterministic asynchronous arrivals
snapshotOffset=[0 .01 -.02 .03;0 -.01 .01 .02];

localGradient=zeros(2,4);
for k=1:4
    localTheta=theta0+snapshotOffset(:,k);
    exactGradient=-2*A'*(A*localTheta-yTarget);
    localGradient(:,k)=exactGradient+.01*randn(2,1); % rollout estimate
end

theta=theta0; currentVersion=globalVersion0;
staleness=nan(1,4); onPolicy=false(1,4); fresh=false(1,4);
accepted=false(1,4);
for arrival=queueOrder
    staleness(arrival)=currentVersion-capturedVersion(arrival);
    onPolicy(arrival)=behaviorVersion(arrival)==policyVersion(arrival);
    fresh(arrival)=staleness(arrival)>=0 && staleness(arrival)<=maxStaleness;
    accepted(arrival)=onPolicy(arrival) && fresh(arrival);
    if accepted(arrival)
        theta=theta+workerStep*localGradient(:,arrival);
        currentVersion=currentVersion+1;
    end
end

beforeObjective=forwardObjective(A,theta0,yTarget);
afterObjective=forwardObjective(A,theta,yTarget);
solverReplay=forwardObjective(A,theta,yTarget); % independent promotion replay
acceptedGradient=mean(localGradient(:,accepted),2);

workers=repmat(struct("worker_id",0,"captured_version",0, ...
    "policy_version",0,"behavior_version",0,"arrival_staleness",0, ...
    "on_policy",false,"fresh",false,"accepted",false, ...
    "local_gradient",zeros(1,2)),4,1);
for k=1:4
    workers(k)=struct("worker_id",k,"captured_version",capturedVersion(k), ...
        "policy_version",policyVersion(k),"behavior_version",behaviorVersion(k), ...
        "arrival_staleness",staleness(k),"on_policy",onPolicy(k), ...
        "fresh",fresh(k),"accepted",accepted(k), ...
        "local_gradient",localGradient(:,k)');
end

checks=struct( ...
    "multiple_workers",numel(workers)>=4, ...
    "arrival_order_is_explicit",isequal(sort(queueOrder),1:4), ...
    "bounded_fresh_workers_accepted",all(accepted([1 2])), ...
    "off_policy_negative_rejected",~accepted(3) && fresh(3) && ~onPolicy(3), ...
    "stale_negative_rejected",~accepted(4) && onPolicy(4) && ~fresh(4), ...
    "version_advanced_only_on_accept",currentVersion-globalVersion0==sum(accepted), ...
    "aggregate_gradient_finite",all(isfinite(acceptedGradient)), ...
    "forward_objective_improved",afterObjective>beforeObjective, ...
    "solver_replay_matches",abs(solverReplay-afterObjective)<1e-12);

report=struct("schema","matlab-acoustic-fembem.a3c-async.v1", ...
    "lesson",struct("video_id","XwYKCiKT7t8", ...
    "public_url","https://www.youtube.com/watch?v=XwYKCiKT7t8", ...
    "principle","asynchronous on-policy workers require version-staleness control"), ...
    "seed",seed,"units",struct("design_parameter","mm", ...
    "forward_response","Pa","objective","-Pa^2","gradient","Pa^2/mm"), ...
    "provenance",struct("source_kind","public_video_metadata", ...
    "catalog","AIcia Solid","transcript_copied",false), ...
    "queue_order",queueOrder,"max_staleness",maxStaleness, ...
    "global_version_before",globalVersion0,"global_version_after",currentVersion, ...
    "workers",workers,"accepted_worker_ids",find(accepted), ...
    "aggregate_gradient",acceptedGradient',"design_before",theta0', ...
    "design_candidate",theta',"forward_objective_before",beforeObjective, ...
    "forward_objective_after",afterObjective,"solver_replay_objective",solverReplay, ...
    "policy_candidate_is_ground_truth",false, ...
    "promotion_requires_forward_solver",true,"checks",checks, ...
    "ok",all(structfun(@logical,checks)));
end

function value=forwardObjective(A,theta,yTarget)
value=-sum((A*theta-yTarget).^2);
end
