function report = activation_probability_gate(seed)
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 223
end
rng(seed,"twister"); x=.37; sigmoid=1/(1+exp(-x)); analytic=sigmoid*(1-sigmoid); h=1e-6;
fd=((1/(1+exp(-(x+h))))-(1/(1+exp(-(x-h)))))/(2*h);
logits=[.2;-.4;1.1]; p=exp(logits-max(logits)); p=p/sum(p); jac=diag(p)-p*p'; fdJac=zeros(3);
for k=1:3, e=zeros(3,1);e(k)=1; pp=softmax(logits+h*e);pm=softmax(logits-h*e);fdJac(:,k)=(pp-pm)/(2*h);end
shifted=softmax(logits+100); saturated=(1/(1+exp(-20)))*(1-1/(1+exp(-20)));
checks=struct("sigmoid_gradient",abs(analytic-fd)<1e-10,"softmax_normalized",abs(sum(p)-1)<1e-12, ...
    "softmax_jacobian",norm(jac-fdJac,"fro")<1e-9,"softmax_shift_invariant",norm(p-shifted)<1e-12, ...
    "saturation_negative_control",saturated<1e-8);
lessons=[struct("video_id","5CwLT-IQB9E","topic","softmax","public_url","https://www.youtube.com/watch?v=5CwLT-IQB9E"); ...
    struct("video_id","gVZ5qCoRxgo","topic","logistic_sigmoid","public_url","https://www.youtube.com/watch?v=gVZ5qCoRxgo")];
report=struct("schema","matlab-acoustic-fembem.activation-probability.v1","lessons",lessons, ...
    "seed",seed,"units",struct("logit","1","probability","1"),"sigmoid",sigmoid, ...
    "sigmoid_gradient_error",abs(analytic-fd),"softmax",p',"softmax_jacobian_error",norm(jac-fdJac,"fro"), ...
    "probability_is_ground_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
function p=softmax(x), e=exp(x-max(x));p=e/sum(e);end
