function report = alphago_cae_search_gate(seed)
%ALPHAGO_CAE_SEARCH_GATE Policy/value/tree-search separation for CAE design.
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 41
end
rng(seed,"twister"); actions=-2:2; na=numel(actions); simulations=240; cpuct=1.4;
target=[.8 -.6]; prior1=softmax(-.8*(actions-target(1)).^2);
n1=zeros(1,na); w1=n1; n2=zeros(na,na); w2=n2;
for s=1:simulations
    q1=w1./max(n1,1); score1=q1+cpuct*prior1.*sqrt(sum(n1)+1)./(1+n1);
    [~,i]=max(score1+1e-12*rand(size(score1)));
    prior2=softmax(-.8*(actions-target(2)).^2);
    q2=w2(i,:)./max(n2(i,:),1);
    score2=q2+cpuct*prior2.*sqrt(sum(n2(i,:))+1)./(1+n2(i,:));
    [~,j]=max(score2+1e-12*rand(size(score2)));
    design=[actions(i) actions(j)]; value=valueNetwork(design,target);
    n1(i)=n1(i)+1; w1(i)=w1(i)+value; n2(i,j)=n2(i,j)+1; w2(i,j)=w2(i,j)+value;
end
[~,iBest]=max(n1); [~,jBest]=max(n2(iBest,:)); candidate=[actions(iBest) actions(jBest)];
solverObjective=forwardSolver(candidate,target);
[g1,g2]=ndgrid(actions,actions); allDesigns=[g1(:) g2(:)];
allObjective=arrayfun(@(k) forwardSolver(allDesigns(k,:),target),1:size(allDesigns,1))';
[globalObjective,kGlobal]=min(allObjective); globalDesign=allDesigns(kGlobal,:);
checks=struct("policy_normalized",abs(sum(prior1)-1)<1e-12, ...
    "search_budget_exact",sum(n1)==simulations, ...
    "candidate_in_action_space",all(ismember(candidate,actions)), ...
    "forward_verified",abs(solverObjective-globalObjective)<1e-12, ...
    "global_design_match",isequal(candidate,globalDesign), ...
    "value_not_ground_truth",true);
report=struct("schema","matlab-acoustic-fembem.alphago-cae-search.v1", ...
    "lesson",struct("video_id","nIfnfN7dY0Y","public_url", ...
    "https://www.youtube.com/watch?v=nIfnfN7dY0Y","principle", ...
    "separate policy prior, value estimate, and tree search"), ...
    "seed",seed,"units",struct("design","1","objective","Pa^2"), ...
    "simulations",simulations,"candidate",candidate,"visit_counts_root",n1, ...
    "policy_prior_root",prior1,"surrogate_role","tree_guidance_only", ...
    "solver_objective",solverObjective,"global_design",globalDesign, ...
    "global_objective",globalObjective,"candidate_is_ground_truth",false, ...
    "promotion_requires_forward_solver",true,"checks",checks,"ok",all(structfun(@logical,checks)));
end
function p=softmax(x), e=exp(x-max(x)); p=e/sum(e); end
function v=valueNetwork(x,t), v=-sum((x-t).^2)+.01*sin(3*x(1)+2*x(2)); end
function f=forwardSolver(x,t), f=sum((x-t).^2); end
