function report = bellman_control_gate(seed)
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 97
end
rng(seed,"twister"); gamma=.9; ns=3; na=2;
next=[2 3;2 3;3 1]; reward=[0 1;.2 .8;0 -.3]; policy=[.6 .4;.5 .5;.7 .3];
ppi=zeros(ns); rpi=zeros(ns,1);
for s=1:ns, for a=1:na, ppi(s,next(s,a))=ppi(s,next(s,a))+policy(s,a); rpi(s)=rpi(s)+policy(s,a)*reward(s,a); end, end
vpi=(eye(ns)-gamma*ppi)\rpi; expectationResidual=norm(vpi-(rpi+gamma*ppi*vpi));
v=zeros(ns,1); residual=zeros(140,1);
for k=1:140
    q=zeros(ns,na); for s=1:ns, for a=1:na, q(s,a)=reward(s,a)+gamma*v(next(s,a)); end, end
    vn=max(q,[],2); residual(k)=norm(vn-v,inf); v=vn;
end
qFinal=zeros(ns,na); for si=1:ns, for ai=1:na, qFinal(si,ai)=reward(si,ai)+gamma*v(next(si,ai)); end, end
optimalResidual=max(abs(v-max(qFinal,[],2))); q=qFinal;
s=1; a=2; sn=next(s,a); qLearningTarget=reward(s,a)+gamma*max(q(sn,:)); sarsaTarget=reward(s,a)+gamma*q(sn,1);
rewards=[.1 .4 -.2]; bootstrap=.7; nstep=sum((gamma.^(0:2)).*rewards)+gamma^3*bootstrap;
behavior=[.5 .5]; target=[.8 .2]; importance=target./behavior;
invalidGamma=1.01; checks=struct("expectation_fixed_point",expectationResidual<1e-12, ...
    "value_iteration_converges",residual(end)<1e-4,"optimal_fixed_point",optimalResidual<1e-4, ...
    "q_and_sarsa_targets_distinct",abs(qLearningTarget-sarsaTarget)>1e-6, ...
    "nstep_finite",isfinite(nstep),"importance_finite",all(isfinite(importance)), ...
    "invalid_discount_rejected",invalidGamma>=1);
ids=["oHm0eNd1yvE","iRhxxRB_TKI","K69r80Ih544","JPt5JYmcngc","Mv62VMRczUo","BYh4uwRgNnk","iMqByZlwHvA","BWcXCecwLcI","7nRgyYjMpas","vvtURKlaVos", ...
    "SI6CfIzEMF8","kpviydgB2KQ","Rlkc50IVK-w","R8CyNE8Vgg4","_DX4HoyjnNU","7ACqHSZwI5M","jwHVLrtkt5w"];
topics=["n_step_td","on_off_policy","sarsa","q_learning","time_domain_bellman_data","value_iteration","policy_iteration","bellman_optimal","bellman_expectation","gpi", ...
    "value_function","discounted_return","policy","mdp","rl_overview","rl_vs_supervised","action_selection_science"];
lessons=repmat(struct("video_id","","topic","","public_url",""),numel(ids),1);
for k=1:numel(ids), lessons(k)=struct("video_id",ids(k),"topic",topics(k),"public_url","https://www.youtube.com/watch?v="+ids(k)); end
report=struct("schema","matlab-acoustic-fembem.bellman-control.v1","lessons",lessons, ...
    "seed",seed,"units",struct("reward","-Pa^2","value","-Pa^2"), ...
    "policy_value",vpi',"optimal_value",v',"expectation_residual",expectationResidual, ...
    "value_iteration_final_residual",residual(end),"q_learning_target",qLearningTarget, ...
    "sarsa_target",sarsaTarget,"n_step_return",nstep,"importance_ratio",importance, ...
    "learned_value_is_ground_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
