function result = capstone_suite_artifact_gate(summary)
%CAPSTONE_SUITE_ARTIFACT_GATE Gate shared-session GYP-091..100 evidence.

checks = struct();
checks.shared_existing_session = startsWith(string(summary.shared_session), "MATLAB_");
checks.release_recorded = contains(string(summary.matlab_version), "R2026a");
checks.execution_route_attach_only = string(summary.execution_route) == ...
    "shared_matlab_engine_existing_session" && logical(summary.attached_only) && ...
    ~logical(summary.engine_quit_called);
checks.shared_java_class_preserved = logical(summary.shared_java_class_available_before) && ...
    logical(summary.shared_java_class_available_after);
checks.source_kind_recorded = string(summary.source_kind) == ...
    "gypsilab_native_gyp_091_100_capstone_suite";
checks.replay_script_recorded = strlength(string(summary.replay_script_sha256)) == 64;
checks.source_ids_exact = isequal(string(summary.source_example_ids(:)), ...
    compose("GYP-%03d", (91:100).'));
mesh = summary.mesh_contract;
checks.vol_tri_tet_p1_contract = string(mesh.format) == ".vol" && ...
    string(mesh.surface) == "tri" && string(mesh.volume) == "tet" && ...
    string(mesh.field_order) == "P1";
caps = summary.capabilities;
checks.ngsolve_capability_query_recorded = logical(caps.ok) && ...
    strlength(string(caps.ngsolve_version)) > 0 && double(caps.mesh_vertices) == 4 && ...
    double(caps.mesh_elements) == 1 && double(caps.h1_dofs) == 4 && ...
    double(caps.hcurl_dofs) == 6 && logical(caps.has_bem) && ...
    logical(caps.has_laplace_sl) && logical(caps.has_helmholtz_sl);
cases = summary.cases;
checks.ten_cases_passed = numel(cases) == 10 && ...
    all(arrayfun(@(row) logical(row.passed), cases));
checks.public_gate_passed = string(summary.public_gate_policy) == ...
    "fem_bem_capstone_suite_gate_v1" && string(summary.public_gate_status) == "ok" && ...
    strlength(string(summary.public_input_sha256)) == 64;
checks.result_sidecar_recorded = logical(summary.json_sidecar_used) && ...
    strlength(string(summary.run_date_utc)) > 0 && ...
    double(summary.timing.total_s) > 0 && ...
    double(summary.timing.ngsolve_capability_query_s) > 0;

names = fieldnames(checks);
values = cellfun(@(name) logical(checks.(name)), names);
result = struct( ...
    "schema", "matlab-fembem-capstone-suite-artifact/v1", ...
    "policy", "shared_engine_gyp_091_100_capstone_gate_v1", ...
    "status", ternary(all(values), "ok", "needs_attention"), ...
    "checks", checks, ...
    "issues", {names(~values)}, ...
    "notes", {{ ...
        "Run the ten capstones with one NGSolve capability query so every case uses the same reference matrices and BEM feature inventory.", ...
        "Preserve the existing Java-enabled MATLAB session and never call Engine quit from the extension.", ...
        "The solver-neutral gate owns matrix, kernel, and trace numerics; this gate owns shared-session and source-suite provenance."}});
end


function value = ternary(condition, yesValue, noValue)
if condition, value = yesValue; else, value = noValue; end
end
