function check_fsi_scattering_invariants(reciprocity_error, optical_error, bem_dtn_error, max_residual, lossless, time_convention)
%CHECK_FSI_SCATTERING_INVARIANTS Print an official-MCP custom-tool verdict.
report = acoustic_fembem.fsi_scattering_invariants_gate( ...
    reciprocity_error, optical_error, bem_dtn_error, max_residual, lossless, time_convention);
fprintf("%s\n", jsonencode(struct( ...
    "tool", "acoustic_fembem_fsi_scattering_invariants", ...
    "ok", report.ok, ...
    "result", report)));
end
