function check_soft_sphere_cq_causality(numTime, timeStep, numGrid)
%CHECK_SOFT_SPHERE_CQ_CAUSALITY Run and report a readable CQ causality gate.

arguments
    numTime (1,1) double {mustBeInteger,mustBeGreaterThan(numTime,3)}
    timeStep (1,1) double {mustBePositive}
    numGrid (1,1) double {mustBeInteger,mustBeGreaterThan(numGrid,3)}
end

repoRoot = acoustic_fembem.repository_root();
addpath(genpath(fullfile(repoRoot, "matlab_api")));
field = softSphereScatterField("NumTime", numTime, "TimeStep", timeStep, "NumGrid", numGrid);
offsetSteps = (field.summary.measured_peak - field.summary.geometric_arrival) / field.time_step;
result = struct( ...
    "schema", "matlab-acoustic-fembem.cq-scattering-arrival.v1", ...
    "status", field.status, ...
    "time_step_s", field.time_step, ...
    "geometric_arrival_s", field.summary.geometric_arrival, ...
    "measured_peak_s", field.summary.measured_peak, ...
    "peak_offset_steps", offsetSteps, ...
    "max_relative_residual", field.summary.max_relative_residual, ...
    "checks", field.checks);
payload = struct("ok", field.status == "ok", ...
    "tool", "acoustic_fembem_soft_sphere_cq_causality", "result", result);
fprintf("%s\n", jsonencode(payload));
end
