function report = cnn_architecture_gate(seed)
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 157
end
rng(seed,"twister"); h=32; w=32; cin=16; cout=32; kernel=3; padding=1; stride=1;
hout=floor((h+2*padding-kernel)/stride)+1; wout=floor((w+2*padding-kernel)/stride)+1;
standardParams=kernel^2*cin*cout; separableParams=kernel^2*cin+cin*cout;
x=randn(8,8,cin); residual=x+zeros(size(x));
squeeze=reshape(mean(x,[1 2]),1,cin); excitation=1./(1+exp(-squeeze)); scaled=x.*reshape(excitation,1,1,cin);
branchChannels=[8 12 4]; inceptionChannels=sum(branchChannels);
checks=struct("convolution_shape",hout==h&&wout==w,"separable_reduces_parameters",separableParams<standardParams, ...
    "zero_residual_identity",max(abs(residual-x),[],"all")==0,"senet_excitation_bounded",all(excitation>0&excitation<1), ...
    "senet_shape_preserved",isequal(size(scaled),size(x)),"inception_concatenates",inceptionChannels==24);
ids=["vDL3Ivtef0U","9KOb-_oy45g","WslQrSO94qE","IANRZujgLT8","p-SflGf3m2Y","KebUnMbOGU8","-tWolA2WvFI", ...
    "GsofrxoAsow","MLixg9K6oeU","vU-JfZNBdYU","FYDJ439Va_Y","Mw4j4yPsFtg","RLlTmbyJORM","SyWwoMpP_P4"];
topics=["senet","xception","resnet","vggnet","googlenet","alexnet","lenet", ...
    "cnn_implementation","pooling","convolution_meaning","fully_connected","depth_by_composition","learning","function_approximator"];
lessons=repmat(struct("video_id","","topic","","public_url",""),numel(ids),1);
for k=1:numel(ids), lessons(k)=struct("video_id",ids(k),"topic",topics(k),"public_url","https://www.youtube.com/watch?v="+ids(k)); end
report=struct("schema","matlab-acoustic-fembem.cnn-architecture.v1","lessons",lessons, ...
    "seed",seed,"units",struct("feature","1","parameter_count","parameter"), ...
    "output_shape",[hout wout cout],"standard_parameters",standardParams,"separable_parameters",separableParams, ...
    "inception_output_channels",inceptionChannels,"cnn_output_is_ground_truth",false, ...
    "promotion_requires_forward_solver",true,"checks",checks,"ok",all(structfun(@logical,checks)));
end
