function result = cq_refinement_artifact_gate(summary)
%CQ_REFINEMENT_ARTIFACT_GATE Gate shared-session coupled CQ evidence.

checks = struct();
checks.shared_existing_session = startsWith(string(summary.shared_session), "MATLAB_");
checks.release_recorded = ~isempty(regexp(string(summary.matlab_version), ...
    "\(R[0-9]{4}[ab]\)", "once"));
checks.attach_only_route = string(summary.execution_route) == ...
    "shared_matlab_engine_existing_session" && logical(summary.attached_only) && ...
    ~logical(summary.engine_quit_called);
checks.shared_java_bridge_preserved = ...
    logical(summary.shared_java_bridge_available_before) && ...
    logical(summary.shared_java_bridge_available_after);
checks.shared_process_and_path_preserved = isequal( ...
    sort(double(summary.matlab_process_ids_before(:))), ...
    sort(double(summary.matlab_process_ids_after(:)))) && ...
    logical(summary.matlab_path_restored);
checks.repository_native_vol_recorded = string(summary.source_kind) == ...
    "repository_native_p1_vol_fem_bem_cq_example" && ...
    strlength(string(summary.vol_sha256)) == 64;

model = summary.model_contract;
checks.p1_johnson_nedelec_cq_model = ...
    string(model.volume_element) == "P1 tetrahedron" && ...
    string(model.boundary_element) == "P1 triangle" && ...
    string(model.coupling) == "JohnsonNedelecCalderon" && ...
    string(model.time_method_family) == "Lubich CQ" && ...
    string(model.absorbing_boundary) == "none";
runs = summary.runs;
names = string({runs.name});
checks.five_required_runs_recorded = numel(runs) == 5 && ...
    isequal(sort(names), sort(["bdf1_coarse","bdf2_coarse", ...
    "bdf2_medium","bdf2_fine","bdf2_medium_replay"]));
checks.all_runs_passed_first_order_coupling = all(arrayfun(@(run) ...
    string(run.status) == "ok" && double(run.num_interior_only_nodes) > 0 && ...
    logical(run.checks.p1_volume_fem) && logical(run.checks.p1_boundary_bem) && ...
    logical(run.checks.johnson_nedelec_calderon_form) && ...
    logical(run.checks.double_layer_k_included), runs));

comparison = summary.comparison;
checks.trusted_window_refinement_recorded = ...
    double(comparison.trusted_window_fraction) == 0.75 && ...
    double(comparison.bdf2_refinement_error_ratio) < 0.9 && ...
    double(comparison.bdf2_coarse_to_fine_relative_error) < ...
    double(comparison.bdf1_coarse_to_bdf2_fine_relative_error);
checks.medium_replay_is_deterministic = ...
    double(comparison.bdf2_medium_replay_relative_error) <= 1e-12;
checks.contour_alias_is_explicit_and_bounded = ...
    double(comparison.contour_alias_target) == 1e-4 && ...
    double(comparison.initial_exterior_relative_amplitude) <= ...
    10 * double(comparison.contour_alias_target);

symbol = summary.symbol_crosscheck;
checks.independent_bdf_symbol_crosscheck_passed = logical(symbol.pass) && ...
    double(symbol.maximum_symbol_relative_error) <= 1e-14 && ...
    logical(symbol.checks.all_laplace_nodes_in_open_right_half_plane) && ...
    logical(symbol.checks.contour_alias_target_is_1e_4);
public = summary.public_gate;
checks.public_cq_refinement_gate_passed = string(public.policy) == ...
    "coupled_cq_refinement_gate_v1" && string(public.status) == "ok";
checks.result_sidecars_and_timing_recorded = logical(summary.json_sidecars_used) && ...
    strlength(string(summary.run_date_utc)) > 0 && ...
    numel(fieldnames(summary.timing_breakdown_s)) == 4 && ...
    all(structfun(@(value) double(value) >= 0, summary.timing_breakdown_s));

names = fieldnames(checks);
values = cellfun(@(name) logical(checks.(name)), names);
result = struct( ...
    "schema", "matlab-coupled-cq-refinement-artifact/v1", ...
    "policy", "shared_engine_coupled_cq_refinement_artifact_gate_v1", ...
    "status", ternary(all(values), "ok", "needs_attention"), ...
    "checks", checks, ...
    "issues", {names(~values)}, ...
    "notes", {{ ...
        "Attach to the existing shared MATLAB session; never clear, quit, or replace its Java bridge.", ...
        "Bind every saved CQ Laplace point to the BDF generating symbol before interpreting the time trace.", ...
        "Use a declared trusted window because rho^-n can amplify round-off near the end of the DFT window.", ...
        "A decreasing refinement error is evidence of trend, not an analytic-accuracy claim."}});
end


function value = ternary(condition, yesValue, noValue)
if condition, value = yesValue; else, value = noValue; end
end
