function result = duct_band_gap_artifact_gate(summary)
%DUCT_BAND_GAP_ARTIFACT_GATE Gate shared-session duct/chain evidence.

checks = struct();
checks.shared_existing_session = startsWith(string(summary.shared_session), "MATLAB_");
checks.release_recorded = ~isempty(regexp(string(summary.matlab_version), ...
    "\(R[0-9]{4}[ab]\)", "once"));
checks.attach_only_route = string(summary.execution_route) == ...
    "shared_matlab_engine_existing_session" && logical(summary.attached_only) && ...
    ~logical(summary.engine_quit_called);
checks.shared_java_bridge_preserved = ...
    logical(summary.shared_java_bridge_available_before) && ...
    logical(summary.shared_java_bridge_available_after);
checks.shared_process_set_preserved = isequal( ...
    sort(double(summary.matlab_process_ids_before(:))), ...
    sort(double(summary.matlab_process_ids_after(:))));

source = summary.source_contract;
checks.repository_native_sources_are_bound = ...
    string(source.kind) == "repository_native_duct_bloch_and_free_space_chain" && ...
    strlength(string(source.generator_sha256)) == 64 && ...
    strlength(string(source.fresh_reference_sha256)) == 64 && ...
    strlength(string(source.chain_vol_sha256)) == 64;
checks.fresh_ngsolve_reference_was_generated = logical(source.regenerated) && ...
    strlength(string(source.ngsolve_version)) > 0 && ...
    double(source.bloch_point_count) == 9 && ...
    double(source.frequency_point_count) == 18 && ...
    double(source.loaded_duct_ndof) >= 25000;

tests = summary.test_evidence;
checks.duct_and_free_space_tests_passed = ...
    double(tests.duct_passed) == 3 && double(tests.duct_failed) == 0 && ...
    double(tests.chain_passed) == 4 && double(tests.chain_failed) == 0;
free = summary.free_space_control;
checks.free_space_control_is_numeric_and_featureless = logical(free.pass) && ...
    numel(free.wavenumbers) == 4 && ...
    double(free.insertion_loss_spread_db) < 1.5 && ...
    double(free.maximum_insertion_loss_db) < 5.0;
public = summary.public_gate;
checks.public_confinement_gate_passed = ...
    string(public.policy) == "acoustic_duct_band_gap_gate_v1" && ...
    string(public.status) == "ok";
checks.result_sidecars_and_four_stage_timing = ...
    logical(summary.json_sidecars_used) && ...
    strlength(string(summary.run_date_utc)) > 0 && ...
    numel(fieldnames(summary.timing_breakdown_s)) == 4 && ...
    all(structfun(@(value) isfinite(double(value)) && double(value) >= 0, ...
    summary.timing_breakdown_s));

names = fieldnames(checks);
values = cellfun(@(name) logical(checks.(name)), names);
result = struct( ...
    "schema", "matlab-acoustic-duct-band-gap-artifact/v1", ...
    "policy", "shared_engine_duct_band_gap_artifact_gate_v1", ...
    "status", ternary(all(values), "ok", "needs_attention"), ...
    "checks", checks, ...
    "issues", {names(~values)}, ...
    "notes", {{ ...
        "Attach to the existing shared MATLAB session and preserve its Java bridge.", ...
        "Regenerate the Bloch/duct reference outside the repository before replaying the saved reference.", ...
        "An empty duct calibrates the port; the free-space chain prevents attenuation from being mislabeled as a band gap."}});
end


function value = ternary(condition, yesValue, noValue)
if condition, value = yesValue; else, value = noValue; end
end
