function report = dueling_cae_action_gate(seed)
%DUELING_CAE_ACTION_GATE Validate Q=V+A for sequential CAE design actions.
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 53
end
rng(seed,"twister");
states=[-1.2;-.6;0;.6;1.2]; actions=[-.4 -.2 0 .2 .4]; target=.35;
q=zeros(numel(states),numel(actions));
for i=1:numel(states)
    for j=1:numel(actions)
        q(i,j)=-forwardObjective(states(i)+actions(j),target)-.02*actions(j)^2;
    end
end

value=mean(q,2); advantage=q-value;
recomposed=value+advantage;
offset=linspace(-2,2,numel(states))';
qShifted=q+offset; shiftedAdvantage=qShifted-mean(qShifted,2);

[~,chosen]=max(recomposed,[],2); chosenActions=actions(chosen)';
solverReward=zeros(size(states)); currentReward=zeros(size(states));
for i=1:numel(states)
    solverReward(i)=-forwardObjective(states(i)+chosenActions(i),target)-.02*chosenActions(i)^2;
    currentReward(i)=-forwardObjective(states(i),target);
end

% Negative controls: raw Q is not a centered advantage; an out-of-contract
% action must never be handed to the solver.
rawAdvantageMean=max(abs(mean(q,2)));
invalidAction=2.5; invalidRejected=~ismember(invalidAction,actions);
checks=struct("advantage_centered",max(abs(mean(advantage,2)))<1e-12, ...
    "q_recomposition",max(abs(recomposed-q),[],"all")<1e-12, ...
    "offset_invariant_advantage",max(abs(shiftedAdvantage-advantage),[],"all")<1e-12, ...
    "uncentered_negative_rejected",rawAdvantageMean>1e-3, ...
    "action_contract_rejects_invalid",invalidRejected, ...
    "solver_replay_matches_q",max(abs(solverReward-max(q,[],2)))<1e-12, ...
    "selected_action_nonworsening",all(solverReward>=currentReward-1e-12), ...
    "selected_action_improves_some",any(solverReward>currentReward+1e-6));

report=struct("schema","matlab-acoustic-fembem.dueling-cae-action.v1", ...
    "lesson",struct("video_id","1nVjUeY1EWU","public_url", ...
    "https://www.youtube.com/watch?v=1nVjUeY1EWU","principle","Q = V + centered A"), ...
    "seed",seed,"units",struct("state","1","action","1","reward","-Pa^2"), ...
    "states",states',"actions",actions,"value",value',"advantage",advantage, ...
    "chosen_actions",chosenActions',"solver_rewards",solverReward', ...
    "current_rewards",currentReward',"raw_advantage_mean_max",rawAdvantageMean, ...
    "invalid_action_negative_control",invalidAction, ...
    "policy_candidate_is_ground_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
function f=forwardObjective(x,target), f=(x-target).^2+.03*x.^4; end
