function result = energy_budget_trace_artifact_gate(summary)
%ENERGY_BUDGET_TRACE_ARTIFACT_GATE Gate shared-session FEM/BEM optimization evidence.

checks = struct();
checks.shared_existing_session = startsWith(string(summary.shared_session), "MATLAB_");
checks.release_recorded = contains(string(summary.matlab_version), "R2026a");
checks.execution_route_attach_only = string(summary.execution_route) == ...
    "shared_matlab_engine_existing_session" && logical(summary.attached_only) && ...
    ~logical(summary.engine_quit_called);
checks.optimization_toolbox_available = logical(summary.optimization_toolbox_license) && ...
    endsWith(string(summary.fmincon_path), fullfile("optimlib", "fmincon.m"), IgnoreCase=true);
preflight = string(summary.pde_geometry_preflight);
checks.pde_preflight_classified = any(preflight == ...
    ["available", "license_present_function_absent", "license_unavailable"]);
checks.geometry_pivot_explained = preflight == "available" || ...
    strlength(string(summary.geometry_pivot_reason)) > 20;
checks.source_kind_recorded = string(summary.source_kind) == ...
    "local_gypsilab_vol_fembem_optimization_example";
checks.replay_script_recorded = strlength(string(summary.replay_script_sha256)) == 64;
checks.generated_vol_not_git_managed = string(summary.vol_artifact_policy) == ...
    "generated_temp_not_git_managed";
checks.random_seed_recorded = double(summary.random_seed) == 647;
mesh = summary.mesh;
checks.vol_identity_recorded = startsWith(string(mesh.source_file_id), "sha256:") && ...
    strlength(extractAfter(string(mesh.source_file_id), "sha256:")) == 64;
checks.tri_tet_p1_contract = string(mesh.volume_element) == "tet4" && ...
    string(mesh.boundary_element) == "tri3" && ...
    string(mesh.volume_basis) == "H1_P1" && ...
    string(mesh.trace_basis) == "scalar_P1" && ...
    double(mesh.points) == double(mesh.h1_dofs) && ...
    double(mesh.trace_dofs) < double(mesh.h1_dofs);
checks.trace_identity_recorded = string(mesh.trace_policy) == ...
    "one_hot_boundary_node_injection_from_vol_node_ids" && ...
    string(mesh.basis_schema) == ...
    "matlab_h1_p1_to_scalar_bem_p1_trace_basis_v1";
checks.problem_contract_recorded = string(summary.objective) == ...
    "0.5*norm(T*u-g)^2" && string(summary.constraint) == ...
    "0.5*u'*Q*u<=energy_budget" && string(summary.energy_operator) == ...
    "H1_P1_stiffness_plus_0.05_mass";
checks.independent_methods_recorded = isequal(sort(string(summary.method_ids(:))), ...
    sort(["analytic_kkt"; "fmincon_sqp"; "fmincon_interior_point"]));
checks.public_gate_passed = string(summary.public_gate_policy) == ...
    "energy_budgeted_trace_kkt_gate_v1" && ...
    string(summary.public_gate_status) == "ok" && ...
    strlength(string(summary.public_input_sha256)) == 64;
checks.result_sidecar_recorded = logical(summary.json_sidecar_used) && ...
    strlength(string(summary.run_date_utc)) > 0 && double(summary.elapsed_s) > 0;

names = fieldnames(checks);
values = cellfun(@(name) logical(checks.(name)), names);
result = struct( ...
    "schema", "matlab-fembem-energy-budget-artifact/v1", ...
    "policy", "shared_engine_vol_trace_fmincon_kkt_gate_v1", ...
    "status", ternary(all(values), "ok", "needs_attention"), ...
    "checks", checks, ...
    "issues", {names(~values)}, ...
    "notes", {{ ...
        "A toolbox license test does not prove the geometry function is installed; classify both checks before choosing the lesson.", ...
        "Keep generated .vol meshes reproducible from the replay script rather than git-managing every mesh output.", ...
        "For an active energy budget, retain primal feasibility, positive dual, stationarity, and complementarity evidence from both fmincon algorithms.", ...
        "The solver-neutral gate owns KKT numerics; this gate owns shared-session, MATLAB function, .vol, and artifact provenance."}});
end


function value = ternary(condition, yesValue, noValue)
if condition, value = yesValue; else, value = noValue; end
end
