function report = factor_rotation_gate(seed)
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 139
end
rng(seed,"twister"); loadings=[.8 .1;.7 .2;.75 .05;.1 .7;.2 .8;.05 .75]; theta=.43; r=[cos(theta) -sin(theta);sin(theta) cos(theta)];
orthogonal=loadings*r; communalBefore=sum(loadings.^2,2); communalAfter=sum(orthogonal.^2,2);
simpleBefore=sum(max(loadings.^2,[],2)); simpleAfter=sum(max(orthogonal.^2,[],2));
promaxMap=[1 .35;0 1]; oblique=orthogonal*promaxMap; phi=inv(promaxMap)*inv(promaxMap)';
covBefore=loadings*loadings'; covOblique=oblique*phi*oblique';
badRotation=[1 1;1 1]; badRejected=rank(badRotation)<2;
checks=struct("orthogonal_communalities",max(abs(communalBefore-communalAfter))<1e-12, ...
    "orthogonal_rotation_unit",norm(r'*r-eye(2),"fro")<1e-12, ...
    "promax_covariance_preserved",norm(covBefore-covOblique,"fro")<1e-12, ...
    "oblique_factor_correlation",abs(phi(1,2))>0,"singular_rotation_rejected",badRejected, ...
    "simple_structure_finite",all(isfinite([simpleBefore simpleAfter])));
ids=["HHpwG5vUskg","ZSZwYpGZSUU","vx9-4xJ-VRo","M6wCZCv28EQ","ZJfytzsqI1o"];
topics=["promax","varimax","factor_rotation","factor_vs_pca","factor_structure_from_correlation"];
lessons=repmat(struct("video_id","","topic","","public_url",""),5,1);
for k=1:5, lessons(k)=struct("video_id",ids(k),"topic",topics(k),"public_url","https://www.youtube.com/watch?v="+ids(k)); end
report=struct("schema","matlab-acoustic-fembem.factor-rotation.v1","lessons",lessons, ...
    "seed",seed,"units",struct("loading","1","covariance","1"), ...
    "communalities_before",communalBefore',"communalities_after",communalAfter', ...
    "promax_covariance_error",norm(covBefore-covOblique,"fro"),"factor_correlation",phi, ...
    "factor_score_is_ground_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
