function report = fsi_scattering_invariants_gate(reciprocity_error, optical_error, bem_dtn_error, max_residual, lossless, time_convention)
%FSI_SCATTERING_INVARIANTS_GATE Gate reciprocal lossless P1 FEM/BEM evidence.
arguments
    reciprocity_error (1,1) double {mustBeFinite,mustBeNonnegative}
    optical_error (1,1) double {mustBeFinite,mustBeNonnegative}
    bem_dtn_error (1,1) double {mustBeFinite,mustBeNonnegative}
    max_residual (1,1) double {mustBeFinite,mustBeNonnegative}
    lossless (1,1) logical
    time_convention (1,1) string
end

invariantTolerance = 0.05;
exteriorTolerance = 0.05;
residualTolerance = 1e-8;
normalizedConvention = lower(erase(erase(strtrim(time_convention), " "), "*"));
recognizedConvention = any(normalizedConvention == ["exp(-iomegat)", "exp(-iwt)", "e^-iwt"]);
checks = struct( ...
    "losslessMaterialDeclared", lossless, ...
    "outgoingTimeConventionExplicit", recognizedConvention, ...
    "farfieldReciprocity", reciprocity_error <= invariantTolerance, ...
    "opticalTheoremEnergyClosure", optical_error <= invariantTolerance, ...
    "p1BemHighOrderDtnAgreement", bem_dtn_error <= exteriorTolerance, ...
    "coupledLinearSystemConverged", max_residual <= residualTolerance);

report = struct( ...
    "schema", "matlab-acoustic-fembem.fsi-scattering-invariants-gate.v1", ...
    "ok", all(structfun(@logical, checks)), ...
    "checks", checks, ...
    "metrics", struct( ...
        "reciprocityRelativeError", reciprocity_error, ...
        "opticalTheoremRelativeError", optical_error, ...
        "bemDtnRelativeError", bem_dtn_error, ...
        "maxSolverResidual", max_residual), ...
    "tolerances", struct( ...
        "maxInvariantError", invariantTolerance, ...
        "maxBemDtnError", exteriorTolerance, ...
        "maxSolverResidual", residualTolerance), ...
    "conventions", struct( ...
        "timeDependence", time_convention, ...
        "reciprocityTransform", "f(obs=b,inc=a)=f(obs=-a,inc=-b)", ...
        "opticalTheorem", "sigma_scat=(4*pi/k)*Im(f_forward)"));
end
