function report = hypothesis_test_gate(seed)
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 131
end
rng(seed,"twister"); n=100; nullSample=randn(n,1); altSample=.7+randn(n,1); alpha=.05;
[z0,p0]=ztestKnown(nullSample); [z1,p1]=ztestKnown(altSample);
mc=randn(5,6000); unbiasedMean=mean(var(mc,0,1)); biasedMean=mean(var(mc,1,1));
checks=struct("null_not_rejected",p0>alpha,"alternative_rejected",p1<alpha, ...
    "p_values_bounded",all([p0 p1]>=0 & [p0 p1]<=1), ...
    "contradiction_requires_threshold",~(p0<alpha)&&p1<alpha, ...
    "n_minus_one_unbiased",abs(unbiasedMean-1)<.03,"divide_by_n_biased",biasedMean<.85);
lessons=[struct("video_id","Af4wIf43MIQ","topic","hypothesis_test_contradiction","public_url","https://www.youtube.com/watch?v=Af4wIf43MIQ"); ...
    struct("video_id","FxJnDJP2jNg","topic","data_scientist_exam","public_url","https://www.youtube.com/watch?v=FxJnDJP2jNg"); ...
    struct("video_id","k9r_qQbZS5Q","topic","degrees_of_freedom","public_url","https://www.youtube.com/watch?v=k9r_qQbZS5Q"); ...
    struct("video_id","x4q4Uaihws4","topic","unbiased_variance_n_minus_one","public_url","https://www.youtube.com/watch?v=x4q4Uaihws4")];
report=struct("schema","matlab-acoustic-fembem.hypothesis-test.v1","lessons",lessons, ...
    "seed",seed,"units",struct("sample","1","p_value","1"),"alpha",alpha, ...
    "null_z",z0,"null_p",p0,"alternative_z",z1,"alternative_p",p1, ...
    "unbiased_variance_mean",unbiasedMean,"biased_variance_mean",biasedMean, ...
    "test_result_is_cae_ground_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
function [z,p]=ztestKnown(x), z=mean(x)/(1/sqrt(numel(x))); p=erfc(abs(z)/sqrt(2)); end
