function report = integrity_encoding_gate(seed)
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 229
end
rng(seed,"twister"); records=["mesh=42","solver=verified","qoi=1.25Pa"]; hashes=zeros(1,3); prev=17;
for k=1:3, hashes(k)=toyHash(records(k),prev);prev=hashes(k);end
tampered=records;tampered(2)="solver=unverified";tamperedHashes=zeros(1,3);prev=17;
for k=1:3,tamperedHashes(k)=toyHash(tampered(k),prev);prev=tamperedHashes(k);end
message="CAE"; bytes=unicode2native(char(message),'UTF-8'); bits=dec2bin(bytes,8); decoded=native2unicode(uint8(bin2dec(bits))','UTF-8');
checks=struct("chain_deterministic",all(isfinite(hashes)),"tamper_detected",any(hashes~=tamperedHashes), ...
    "downstream_link_changes",hashes(3)~=tamperedHashes(3),"binary_roundtrip",string(decoded)==message, ...
    "production_crypto_claim_rejected",true);
lessons=[struct("video_id","bclE3gLeyzg","topic","blockchain","public_url","https://www.youtube.com/watch?v=bclE3gLeyzg"); ...
    struct("video_id","3Vzym-DvVyU","topic","text_binary_encoding","public_url","https://www.youtube.com/watch?v=3Vzym-DvVyU")];
report=struct("schema","matlab-acoustic-fembem.integrity-encoding.v1","lessons",lessons, ...
    "seed",seed,"units",struct("hash","educational_checksum","encoding","UTF-8"), ...
    "hashes",hashes,"tampered_hashes",tamperedHashes,"decoded",string(decoded), ...
    "warning","toy rolling checksum; not production cryptography", ...
    "integrity_record_is_solver_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
function h=toyHash(text,previous), prime=2147483647; vals=double(char(text));h=previous;for i=1:numel(vals),h=mod(131*h+vals(i),prime);end,end
