function report = latent_distribution_gate(seed)
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 73
end
rng(seed,"twister"); prior=[.35 .65]; mu=[-1 1.2]; sigma=.3; x=.4;
like=exp(-.5*((x-mu)/sigma).^2)/(sqrt(2*pi)*sigma);
posterior=prior.*like/sum(prior.*like);
z=double(rand(500,1)>prior(1))+1; generated=mu(z)'+sigma*randn(500,1);
modeFreq=[mean(z==1) mean(z==2)]; qoi=(generated-.25).^2;
checks=struct("prior_normalized",abs(sum(prior)-1)<1e-12, ...
    "posterior_normalized",abs(sum(posterior)-1)<1e-12, ...
    "generation_matches_prior",max(abs(modeFreq-prior))<.08, ...
    "identification_prefers_likely_mode",posterior(2)>posterior(1), ...
    "forward_qoi_finite",all(isfinite(qoi)));
report=struct("schema","matlab-acoustic-fembem.latent-distribution.v1", ...
    "lessons",[struct("video_id","WSPhuhtlDRA","topic","generation_and_identification","public_url","https://www.youtube.com/watch?v=WSPhuhtlDRA"); ...
    struct("video_id","cav2X8Zd6ps","topic","generative_models_as_distributions","public_url","https://www.youtube.com/watch?v=cav2X8Zd6ps")], ...
    "seed",seed,"units",struct("latent","1","observation","Pa","qoi","Pa^2"), ...
    "prior",prior,"posterior",posterior,"sample_mode_frequency",modeFreq, ...
    "generated_candidate_is_ground_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
