function result = linear_magnet_artifact_gate(summary)
%LINEAR_MAGNET_ARTIFACT_GATE Gate a shared-session linear magnet replay.

checks = struct();
checks.shared_existing_session = startsWith(string(summary.shared_session), "MATLAB_");
checks.release_recorded = ~isempty(regexp(string(summary.matlab_version), ...
    "\(R[0-9]{4}[ab]\)", "once"));
checks.execution_route_attach_only = string(summary.execution_route) == ...
    "shared_matlab_engine_existing_session" && logical(summary.attached_only) && ...
    ~logical(summary.engine_quit_called);
checks.shared_java_bridge_preserved = ...
    logical(summary.shared_java_bridge_available_before) && ...
    logical(summary.shared_java_bridge_available_after);

mcp = summary.mcp_runtime;
checks.official_mcp_capture_route = string(mcp.server_version) == "0.11.2" && ...
    string(mcp.session_mode) == "auto" && ...
    string(mcp.display_mode) == "nodesktop" && ...
    logical(mcp.preflight_single_shared_session) && ...
    string(mcp.preflight_shared_session) == string(summary.shared_session) && ...
    logical(mcp.attached_existing) && logical(mcp.capture_feval_passed);
checks.shared_process_set_preserved = isequal( ...
    sort(double(mcp.matlab_process_ids_before(:))), ...
    sort(double(mcp.matlab_process_ids_after(:))));

checks.source_native_example_recorded = string(summary.source_kind) == ...
    "source_native_matlab_magnet_example" && ...
    strlength(string(summary.source_sha256)) == 64;
migration = summary.migration;
checks.migration_is_path_and_ui_only = ...
    logical(migration.hardcoded_path_replaced) && ...
    logical(migration.gui_call_suppressed) && ...
    ~logical(migration.geometry_changed) && ...
    ~logical(migration.materials_changed) && ...
    ~logical(migration.boundary_conditions_changed);

mesh = summary.mesh;
checks.p1_triangle_mesh_recorded = string(mesh.element_type) == "TL3" && ...
    double(mesh.node_count) > 0 && double(mesh.element_count) > 0 && ...
    double(mesh.boundary_node_count) > 0;
checks.two_source_levels_recorded = isequal(double(summary.scale_factors(:)), [1; 0.5]);

public = summary.public_gate;
checks.public_scaling_gate_passed = string(public.policy) == ...
    "linear_magnetization_scaling_gate_v1" && string(public.status) == "ok" && ...
    strlength(string(summary.public_input_sha256)) == 64;
checks.live_identity_checks_passed = all(structfun(@logical, summary.live_checks));
checks.result_sidecar_recorded = logical(summary.json_sidecar_used) && ...
    strlength(string(summary.run_date_utc)) > 0 && ...
    double(summary.timing.geometry_setup_s) >= 0 && ...
    double(summary.timing.mesh_generation_s) > 0 && ...
    double(summary.timing.full_scale_solve_s) > 0 && ...
    double(summary.timing.half_scale_solve_s) > 0;

names = fieldnames(checks);
values = cellfun(@(name) logical(checks.(name)), names);
result = struct( ...
    "schema", "matlab-linear-magnet-artifact/v1", ...
    "policy", "shared_engine_linear_magnet_scaling_gate_v1", ...
    "status", ternary(all(values), "ok", "needs_attention"), ...
    "checks", checks, ...
    "issues", {names(~values)}, ...
    "notes", {{ ...
        "Attach to the one existing shared MATLAB session and preserve its Java bridge.", ...
        "A source-native example may be migrated by replacing a fixed path and suppressing its GUI, while geometry, material assignment, and boundary conditions remain unchanged.", ...
        "Use the same P1 triangle mesh for both source levels; fieldwise A/B errors and quadratic energy scaling are stronger than comparing scalar maxima alone.", ...
        "The public solver-neutral gate owns the physical scaling identity; this gate owns MATLAB session, migration, mesh, and artifact provenance."}});
end


function value = ternary(condition, yesValue, noValue)
if condition, value = yesValue; else, value = noValue; end
end
