function result = lsqnonlin_multistart_artifact_gate(summary)
%LSQNONLIN_MULTISTART_ARTIFACT_GATE Gate shared-session lsqnonlin evidence.

checks = struct();
checks.shared_existing_session = startsWith(string(summary.shared_session), "MATLAB_");
checks.release_recorded = strlength(string(summary.matlab_version)) > 0;
checks.shared_solver_session_survived = logical(summary.shared_solver_connected_before) && ...
    logical(summary.shared_solver_connected_after);
checks.source_kind_recorded = string(summary.source_kind) == ...
    "source_native_matlab_optimization_example";
digests = string(struct2cell(summary.source_digests));
checks.source_digests_recorded = numel(digests) >= 2 && all(strlength(digests) == 64);
checks.source_copy_preserved = logical(summary.source_copy_preserved);
checks.optimization_toolbox_available = logical(summary.optimization_toolbox_license);
checks.lsqnonlin_resolved = endsWith(string(summary.lsqnonlin_path), ...
    fullfile("optimlib", "lsqnonlin.m"), IgnoreCase=true);
checks.zero_multiplicative_start_pathology_recorded = ...
    string(summary.legacy_start_rule) == "x=x.*(1+10*rand(size(x)))" && ...
    double(summary.legacy_start_count) >= 4 && logical(summary.legacy_all_zero);
checks.independent_multistart_recorded = ...
    string(summary.corrected_start_rule) == "independent_seeded_starts" && ...
    double(summary.corrected_start_count) >= 4 && ...
    logical(summary.corrected_starts_distinct);
checks.residual_gate_passed = double(summary.max_residual_norm) <= ...
    double(summary.residual_norm_tolerance);
checks.stationarity_gate_passed = double(summary.max_projected_gradient_inf_norm) <= ...
    double(summary.projected_gradient_tolerance);
checks.solver_jacobian_gate_passed = double(summary.max_solver_jacobian_relative_error) <= ...
    double(summary.solver_jacobian_tolerance);
checks.finite_difference_jacobian_gate_passed = ...
    double(summary.max_finite_difference_jacobian_relative_error) <= ...
    double(summary.finite_difference_jacobian_tolerance);
checks.sparse_jacobian_json_contract = ...
    logical(summary.sparse_jacobian_converted_to_full_before_jsonencode);
checks.python_engine_sidecar_contract = double(summary.python_engine_nargout) == 0 && ...
    logical(summary.json_sidecar_used);
checks.attach_only_contract = logical(summary.attached_only) && ...
    ~logical(summary.engine_quit_called) && ...
    logical(summary.engine_connection_released_without_quit);
checks.public_gate_passed = ...
    string(summary.public_gate_schema) == "radia-topology-nonlinear-lsq-multistart/v1" && ...
    string(summary.public_gate_status) == "ok" && ...
    strlength(string(summary.public_input_sha256)) == 64;
checks.result_date_recorded = strlength(string(summary.run_date_utc)) > 0;

names = fieldnames(checks);
values = cellfun(@(name) logical(checks.(name)), names);
result = struct( ...
    "schema", "matlab-lsqnonlin-multistart-artifact/v1", ...
    "policy", "shared_engine_attach_only_lsqnonlin_jacobian_gate_v1", ...
    "status", ternary(all(values), "ok", "needs_attention"), ...
    "checks", checks, ...
    "issues", {names(~values)}, ...
    "notes", {{ ...
        "Multiplying an all-zero vector by random factors leaves every multistart at zero.", ...
        "lsqnonlin returns a residual Jacobian; verify it against analytic and finite-difference Jacobians.", ...
        "Convert sparse Jacobians to full before jsonencode and use a JSON sidecar for Python Engine struct arrays.", ...
        "Attach to the existing solver-connected MATLAB Engine and release the client without calling quit."}});
end


function value = ternary(condition, yesValue, noValue)
if condition, value = yesValue; else, value = noValue; end
end
