function report = pca_covariance_gate(seed)
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 103
end
rng(seed,"twister"); n=800; x=randn(n,3)*[2 0 0;0 .7 0;0 0 .2]*orth(randn(3)); x=x-mean(x,1);
c=cov(x); [q,d]=eig(c,"vector"); [d,ord]=sort(d,"descend"); q=q(:,ord);
pcVariance=var(x*q(:,1),1); randomVariance=zeros(500,1);
for k=1:500, a=randn(3,1); a=a/norm(a); randomVariance(k)=var(x*a,1); end
recon=zeros(1,3);
for r=1:3, xr=(x*q(:,1:r))*q(:,1:r)'; recon(r)=mean((xr-x).^2,"all"); end
u=x(:,1); v=x(:,2); covarianceDot=(u'*v)/(n-1); correlationCos=(u'*v)/(norm(u)*norm(v)); correlationManual=c(1,2)/(std(u)*std(v));
checks=struct("covariance_symmetric",norm(c-c',"fro")<1e-12, ...
    "eigenvectors_orthogonal",norm(q'*q-eye(3),"fro")<1e-12, ...
    "pc1_maximizes_sampled_variance",pcVariance>=max(randomVariance)-1e-10, ...
    "reconstruction_monotone",all(diff(recon)<=1e-12), ...
    "full_rank_reconstructs",recon(3)<1e-25, ...
    "covariance_dot_identity",abs(covarianceDot-c(1,2))<1e-12, ...
    "correlation_cosine_identity",abs(correlationCos-correlationManual)<1e-12);
ids=["R5oOco7BG2E","F1UcwlLfcfk","0s_MDakfcvI","BfHZEaa4WD0","Wp8YtVPF1cM","AQVFMYIzyo8","fkvArkvQs9Y","2T7hmLXbLhg","tXvmQ1XFRpo", ...
    "e61089Wkoy0","5ij6jXmv-gA","M6wCZCv28EQ","mMmTHoZKWTI","1cilW3CMBvw"];
topics=["pca","symmetric_diagonalization_6","component_extraction","relation_decomposition","symmetric_relation","orthogonal_matrix","symmetric_matrix","covariance_geometry","covariance_algebra", ...
    "covariance_meaning","covariance_variables","factor_vs_pca","pca_correlation_compression","correlation_spreadsheet"];
lessons=repmat(struct("video_id","","topic","","public_url",""),numel(ids),1);
for k=1:numel(ids), lessons(k)=struct("video_id",ids(k),"topic",topics(k),"public_url","https://www.youtube.com/watch?v="+ids(k)); end
report=struct("schema","matlab-acoustic-fembem.pca-covariance.v1","lessons",lessons, ...
    "seed",seed,"units",struct("sample","Pa","variance","Pa^2"), ...
    "eigenvalues",d',"pc1_variance",pcVariance,"max_random_variance",max(randomVariance), ...
    "reconstruction_mse",recon,"covariance_dot",covarianceDot,"correlation_cosine",correlationCos, ...
    "pca_candidate_is_ground_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
