function result = periodic_pm_machine_artifact_gate(summary)
%PERIODIC_PM_MACHINE_ARTIFACT_GATE Gate shared-session PM-machine replay.

checks = struct();
checks.shared_existing_session = startsWith(string(summary.shared_session), "MATLAB_");
checks.release_recorded = ~isempty(regexp(string(summary.matlab_version), ...
    "\(R[0-9]{4}[ab]\)", "once"));
checks.execution_route_attach_only = string(summary.execution_route) == ...
    "shared_matlab_engine_existing_session" && logical(summary.attached_only) && ...
    ~logical(summary.engine_quit_called);
checks.shared_java_bridge_preserved = ...
    logical(summary.shared_java_bridge_available_before) && ...
    logical(summary.shared_java_bridge_available_after);
checks.shared_process_set_preserved = isequal( ...
    sort(double(summary.matlab_process_ids_before(:))), ...
    sort(double(summary.matlab_process_ids_after(:))));

checks.source_native_example_recorded = string(summary.source_kind) == ...
    "source_native_unwrapped_pm_machine_example" && ...
    strlength(string(summary.source_sha256)) == 64;
migration = summary.migration;
checks.migration_is_path_and_ui_only = ...
    logical(migration.hardcoded_path_replaced) && ...
    logical(migration.gui_call_suppressed) && ...
    logical(migration.function_workspace_isolation) && ...
    ~logical(migration.geometry_changed) && ...
    ~logical(migration.materials_changed) && ...
    ~logical(migration.boundary_conditions_changed);

model = summary.model;
checks.source_topology_recorded = double(model.slot_count) == 12 && ...
    double(model.pole_count) == 10 && ...
    string(model.mesh_element_type) == "TL3" && ...
    double(model.periodic_master_count) > 0 && ...
    double(model.periodic_master_count) == double(model.periodic_slave_count);
diagnostic = summary.symmetry_diagnostic;
checks.one_pole_claim_explicitly_rejected = ...
    string(diagnostic.rejected_shift) == "one_pole_pitch" && ...
    double(diagnostic.one_pole_relative_error) > double(diagnostic.one_pole_tolerance) && ...
    logical(diagnostic.rejection_recorded);
checks.half_turn_symmetry_promoted = ...
    string(diagnostic.accepted_shift) == "half_circumference" && ...
    double(diagnostic.half_turn_relative_error) <= double(diagnostic.half_turn_tolerance);

checks.two_live_replays_recorded = numel(summary.runs) == 2 && ...
    all(arrayfun(@(run) logical(run.pass) && double(run.node_count) > 100 && ...
    double(run.element_count) > 100 && double(run.energy_j) > 0 && ...
    double(run.coenergy_j) > 0, summary.runs));
checks.replay_observables_passed = all(structfun(@logical, summary.replay_checks));
public = summary.public_gate;
checks.public_periodicity_gate_passed = string(public.policy) == ...
    "periodic_unwrapped_pm_machine_replay_gate_v1" && ...
    string(public.status) == "ok" && ...
    strlength(string(summary.public_input_sha256)) == 64;
checks.result_sidecars_and_timing_recorded = logical(summary.json_sidecars_used) && ...
    strlength(string(summary.run_date_utc)) > 0 && ...
    numel(fieldnames(summary.timing_breakdown_s)) == 4 && ...
    all(structfun(@(value) double(value) >= 0, summary.timing_breakdown_s));

names = fieldnames(checks);
values = cellfun(@(name) logical(checks.(name)), names);
result = struct( ...
    "schema", "matlab-periodic-pm-machine-artifact/v1", ...
    "policy", "shared_engine_periodic_pm_machine_artifact_gate_v1", ...
    "status", ternary(all(values), "ok", "needs_attention"), ...
    "checks", checks, ...
    "issues", {names(~values)}, ...
    "notes", {{ ...
        "Run source-native scripts in an isolated function workspace; never clear or quit the shared MATLAB session.", ...
        "A one-pole shift changes rotor polarity but does not generally reproduce the stator-slot geometry.", ...
        "For a 12-slot/10-pole full model, the half turn repeats six slots and reverses five poles, so the air-gap field is antiperiodic.", ...
        "An unseeded teaching mesher may change cardinality; gate replay on energy and field observables."}});
end


function value = ternary(condition, yesValue, noValue)
if condition, value = yesValue; else, value = noValue; end
end
