function report = policy_trust_gate(seed)
%POLICY_TRUST_GATE DPG gradient and TRPO KL trust-region controls.
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 67
end
rng(seed,"twister"); s=linspace(-1,1,101)'; target=.7*s+.15; theta=.2;
objective=@(th) mean(-((th*s)-target).^2);
analytic=mean(-2*(theta*s-target).*s); h=1e-6;
fd=(objective(theta+h)-objective(theta-h))/(2*h); gradErr=abs(analytic-fd)/max(abs(fd),1e-12);

sigma=.25; proposed=theta+1.2*analytic; kl=@(th) mean(((th*s-theta*s).^2)/(2*sigma^2));
delta=.01; proposedKl=kl(proposed); scale=min(1,sqrt(delta/max(proposedKl,eps))*.99);
trusted=theta+scale*(proposed-theta); trustedKl=kl(trusted);

onlineTarget=1.1; targetOld=-.4; tau=.05; targetNew=(1-tau)*targetOld+tau*onlineTarget;
softDistanceOld=abs(targetOld-onlineTarget); softDistanceNew=abs(targetNew-onlineTarget);
invalidAction=3; actionBounds=[-1 1]; invalidRejected=invalidAction<actionBounds(1)||invalidAction>actionBounds(2);
checks=struct("dpg_gradient_matches_fd",gradErr<1e-8, ...
    "untrusted_step_exceeds_kl",proposedKl>delta, ...
    "trusted_step_within_kl",trustedKl<=delta, ...
    "trusted_objective_improves",objective(trusted)>objective(theta), ...
    "soft_target_contracts",softDistanceNew<softDistanceOld, ...
    "invalid_action_rejected",invalidRejected);
report=struct("schema","matlab-acoustic-fembem.policy-trust.v1", ...
    "lessons",[struct("video_id","S1oZmLAvDVI","topic","ddpg","public_url","https://www.youtube.com/watch?v=S1oZmLAvDVI"); ...
    struct("video_id","1pw0Fgu7y60","topic","trpo","public_url","https://www.youtube.com/watch?v=1pw0Fgu7y60"); ...
    struct("video_id","5SgBrP4UYgQ","topic","deterministic_policy_gradient_proof","public_url","https://www.youtube.com/watch?v=5SgBrP4UYgQ")], ...
    "seed",seed,"units",struct("state","1","action","1","reward","-Pa^2"), ...
    "dpg_gradient",analytic,"gradient_fd",fd,"gradient_relative_error",gradErr, ...
    "proposed_kl",proposedKl,"trusted_kl",trustedKl,"kl_limit",delta, ...
    "objective_before",objective(theta),"objective_after",objective(trusted), ...
    "policy_candidate_is_ground_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
