function report = projective_geometry_gate(seed)
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 151
end
rng(seed,"twister"); p=[.4;-.2;1]; scaled=3.7*p; affine=p(1:2)/p(3); affineScaled=scaled(1:2)/scaled(3);
h=[1 .2 .1;-.1 .9 .3;.02 -.03 1]; hp=h*p; pBack=h\hp; pBack=pBack/pBack(3);
c=diag([1 1 -1]); cTransformed=inv(h)'*c*inv(h); incidenceBefore=p'*c*p; incidenceAfter=hp'*cTransformed*hp;
bad=[1 0 0;0 1 0;0 0 0]; badRejected=rank(bad)<3;
checks=struct("homogeneous_scale_invariant",norm(affine-affineScaled)<1e-12, ...
    "homography_roundtrip",norm(pBack-p)<1e-12,"conic_incidence_invariant",abs(incidenceBefore-incidenceAfter)<1e-12, ...
    "singular_homography_rejected",badRejected,"transformed_conic_symmetric",norm(cTransformed-cTransformed',"fro")<1e-12);
report=struct("schema","matlab-acoustic-fembem.projective-geometry.v1", ...
    "lesson",struct("video_id","aa4PMb8C4AM","topic","projective_geometry","public_url","https://www.youtube.com/watch?v=aa4PMb8C4AM"), ...
    "seed",seed,"units",struct("homogeneous_coordinate","1"),"roundtrip_error",norm(pBack-p), ...
    "incidence_error",abs(incidenceBefore-incidenceAfter),"geometry_candidate_is_ground_truth",false, ...
    "promotion_requires_forward_solver",true,"checks",checks,"ok",all(structfun(@logical,checks)));
end
