function report = random_matrix_stability_gate(seed)
%RANDOM_MATRIX_STABILITY_GATE Gradient vanishing/explosion controls.
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 89
end
rng(seed,"twister"); n=12; layers=25;
pStable=eye(n); pExplode=eye(n); pVanish=eye(n);
for k=1:layers
    [q,~]=qr(randn(n));
    pStable=q*pStable; pExplode=(1.15*q)*pExplode; pVanish=(.85*q)*pVanish;
end
sStable=svd(pStable); sExplode=svd(pExplode); sVanish=svd(pVanish);
v=randn(n,1); stableRatio=norm(pStable*v)/norm(v);
checks=struct("orthogonal_singular_values",max(abs(sStable-1))<1e-10, ...
    "stable_sensitivity",abs(stableRatio-1)<1e-10, ...
    "explosion_negative_control",max(sExplode)>20, ...
    "vanishing_negative_control",max(sVanish)<.03, ...
    "finite_products",all(isfinite([sStable;sExplode;sVanish])));
report=struct("schema","matlab-acoustic-fembem.random-matrix-stability.v1", ...
    "lesson",struct("video_id","X6KOlZFf4mk","topic","random_matrices_and_deep_learning", ...
    "public_url","https://www.youtube.com/watch?v=X6KOlZFf4mk"), ...
    "seed",seed,"units",struct("state","1","sensitivity","1"),"layers",layers, ...
    "stable_singular_range",[min(sStable) max(sStable)], ...
    "exploding_max_singular",max(sExplode),"vanishing_max_singular",max(sVanish), ...
    "network_candidate_is_ground_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
