function report = rl_stability_gate(seed)
%RL_STABILITY_GATE PER importance weights and Double-DQN bias controls.
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 59
end
rng(seed,"twister");

td=[.01 .05 .2 .7 2.5]; alpha=.7; beta=1;
priority=(abs(td)+1e-3).^alpha; probability=priority/sum(priority);
weight=(numel(td)*probability).^(-beta); weight=weight/max(weight);
uniformMean=mean(td); correctedMean=sum(probability.*weight.*td)/sum(probability.*weight);

n=12000; na=5; onlineNoise=randn(n,na); targetNoise=randn(n,na);
dqnTarget=max(targetNoise,[],2);
[~,choice]=max(onlineNoise,[],2);
idx=sub2ind(size(targetNoise),(1:n)',choice);
doubleTarget=targetNoise(idx);
dqnBias=mean(dqnTarget); doubleBias=mean(doubleTarget);

invalidPriority=-.2; invalidRejected=invalidPriority<0;
checks=struct("probability_normalized",abs(sum(probability)-1)<1e-12, ...
    "high_td_sampled_more",probability(end)>probability(1), ...
    "importance_correction",abs(correctedMean-uniformMean)<1e-12, ...
    "negative_priority_rejected",invalidRejected, ...
    "dqn_overestimation_visible",dqnBias>.5, ...
    "double_dqn_reduces_bias",abs(doubleBias)<.08*dqnBias, ...
    "solver_target_finite",all(isfinite([dqnTarget;doubleTarget])));

report=struct("schema","matlab-acoustic-fembem.rl-stability.v1", ...
    "lessons",[struct("video_id","ZLt_YLUbTKI","topic","prioritized_experience_replay", ...
    "public_url","https://www.youtube.com/watch?v=ZLt_YLUbTKI"); ...
    struct("video_id","XpP2VllJhBM","topic","double_dqn", ...
    "public_url","https://www.youtube.com/watch?v=XpP2VllJhBM")], ...
    "seed",seed,"units",struct("td_error","Pa^2","target","-Pa^2"), ...
    "td_errors",td,"sampling_probability",probability,"importance_weight",weight, ...
    "uniform_td_mean",uniformMean,"corrected_td_mean",correctedMean, ...
    "dqn_overestimation_bias",dqnBias,"double_dqn_bias",doubleBias, ...
    "learned_target_is_ground_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
