function result = rwg_hcurl_trace_artifact_gate(summary)
%RWG_HCURL_TRACE_ARTIFACT_GATE Gate shared-session GYP-081..090 evidence.

checks = struct();
checks.shared_existing_session = startsWith(string(summary.shared_session), "MATLAB_");
checks.release_recorded = ~isempty(regexp(string(summary.matlab_version), ...
    "\(R[0-9]{4}[ab]\)", "once"));
checks.execution_route_attach_only = string(summary.execution_route) == ...
    "shared_matlab_engine_existing_session" && logical(summary.attached_only) && ...
    ~logical(summary.engine_quit_called);
checks.shared_java_bridge_preserved = ...
    logical(summary.shared_java_bridge_available_before) && ...
    logical(summary.shared_java_bridge_available_after);
mcp = summary.mcp_runtime;
checks.official_mcp_capture_route = string(mcp.server_version) == "0.11.2" && ...
    string(mcp.session_mode) == "auto" && ...
    string(mcp.display_mode) == "nodesktop" && ...
    logical(mcp.preflight_single_shared_session) && ...
    string(mcp.preflight_shared_session) == string(summary.shared_session) && ...
    logical(mcp.attached_existing) && logical(mcp.capture_feval_passed) && ...
    logical(mcp.desktop_eval_failure_reproduced);
checks.shared_process_set_preserved = isequal( ...
    sort(double(mcp.matlab_process_ids_before(:))), ...
    sort(double(mcp.matlab_process_ids_after(:))));
checks.source_kind_recorded = string(summary.source_kind) == ...
    "gypsilab_native_gyp_081_090_rwg_hcurl_suite";
checks.replay_script_recorded = strlength(string(summary.replay_script_sha256)) == 64;
checks.source_ids_exact = isequal(string(summary.source_example_ids(:)), ...
    compose("GYP-%03d", (81:90).'));
mesh = summary.mesh_contract;
checks.vol_tri_tet_first_order_contract = string(mesh.format) == ".vol" && ...
    string(mesh.surface) == "tri" && string(mesh.volume) == "tet" && ...
    string(mesh.field_order) == "P1" && ...
    string(mesh.volume_edge_space) == "Nedelec0" && ...
    string(mesh.boundary_vector_space) == "RWG0";
caps = summary.capabilities;
checks.ngsolve_hcurl_reference_recorded = logical(caps.ok) && ...
    strlength(string(caps.ngsolve_version)) > 0 && double(caps.hcurl_dofs) == 6;
checks.maxwell_bem_not_overclaimed = logical(caps.has_maxwell_sl) || ...
    ~logical(summary.maxwell_bem_claimed);
cases = summary.cases;
checks.ten_source_cases_passed = numel(cases) == 10 && ...
    all(arrayfun(@(row) logical(row.passed), cases));
trace = summary.trace_diagnostics;
checks.trace_inventory_recorded = double(trace.rwg_dofs) == 6 && ...
    double(trace.hcurl_dofs) == 6 && double(trace.selector_nonzeros) == 6 && ...
    double(trace.rotated_trace_nonzeros) == 6 && double(trace.rotated_trace_rank) == 6;
tests = summary.matlab_tests;
checks.related_tests_passed = double(tests.test_count) >= 1 && ...
    double(tests.passed) == double(tests.test_count) && ...
    double(tests.failed) == 0 && double(tests.incomplete) == 0;
public = summary.public_gate;
checks.public_trace_gate_passed = string(public.policy) == ...
    "rwg_hcurl_trace_consistency_gate_v1" && string(public.status) == "ok" && ...
    logical(public.solver_ready) && strlength(string(summary.public_input_sha256)) == 64;
checks.result_sidecar_recorded = logical(summary.json_sidecar_used) && ...
    strlength(string(summary.run_date_utc)) > 0 && double(summary.timing.total_s) > 0 && ...
    double(summary.timing.ngsolve_capability_query_s) > 0 && ...
    double(summary.timing.trace_diagnostics_s) > 0 && ...
    double(summary.timing.matlab_tests_s) > 0;

names = fieldnames(checks);
values = cellfun(@(name) logical(checks.(name)), names);
result = struct( ...
    "schema", "matlab-rwg-hcurl-trace-artifact/v1", ...
    "policy", "shared_engine_gyp_081_090_rwg_hcurl_gate_v1", ...
    "status", ternary(all(values), "ok", "needs_attention"), ...
    "checks", checks, ...
    "issues", {names(~values)}, ...
    "notes", {{ ...
        "Run GYP-081..090 in the already shared MATLAB session and preserve its Java bridge.", ...
        "For official MCP v0.11.2 on this R2026a lane, preflight one shared session, use auto plus nodesktop to select capture FEval, and prove the server attached without changing the MATLAB process set.", ...
        "Keep the .vol tri/tet first-order contract explicit: Nedelec0 in the volume and RWG0 on the boundary.", ...
        "The solver-neutral gate owns edge identity, rotated trace scaling, Gram positivity, de Rham closure, and NGSolve matrix comparison.", ...
        "Do not claim Maxwell BEM when the independent capability query reports it unavailable."}});
end


function value = ternary(condition, yesValue, noValue)
if condition, value = yesValue; else, value = noValue; end
end
