function report = spectral_linear_algebra_gate(seed)
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 101
end
rng(seed,"twister"); a=randn(7,4); [u,s,v]=svd(a,"econ"); reconstruct=norm(a-u*s*v',"fro")/norm(a,"fro");
x=randn(4,1); components=u*(s*(v'*x)); componentError=norm(a*x-components)/norm(a*x);
z=randn(4,1); isometryU=abs(norm(u*z)-norm(z)); isometryV=abs(norm(v*z)-norm(z));
h=randn(5); h=(h+h')/2; [q,d]=eig(h); diagonalError=norm(h-q*d*q',"fro")/norm(h,"fro");
c=randn(4); c=c*c'+.2*eye(4); [l,p]=chol(c,"lower"); bad=c; bad(1,1)=-1; [~,pBad]=chol(bad);
samples=randn(4000,4)*l'; whitened=(samples-mean(samples,1))/l'; whiteError=norm(cov(whitened)-eye(4),"fro");
checks=struct("svd_reconstruction",reconstruct<1e-12,"svd_component_formula",componentError<1e-12, ...
    "orthogonal_isometry",max([isometryU isometryV])<1e-12,"symmetric_diagonalization",diagonalError<1e-12, ...
    "covariance_spd",p==0,"invalid_covariance_rejected",pBad>0,"whitening_close",whiteError<.08, ...
    "weitzenbock_triangle",weitzenbockCheck());
ids=["XnRP8oskIOI","t_kCvNJWGgc","vrhO8g0Bj1I","UBIEh7V2JCg","F06wnWYlhI8","6L9n01lny98","sLAmM48R20k","7Fg9J5Elhow", ...
    "TrezMf--eq4","YVIMrAzAG5s","G_5qattH6Bw","2FHmdkEl-jQ","5dJAh9EzpV0","Sw9ph4465dg","eZWh8jMSlZM","xM_fYlreWCU","wVipLySksnE","NjS6-tleDX0","xSoAy0wXu8s","p80YL5x_FpI"];
topics=["orthogonal_isometry","svd_factor_meaning","general_vector_transform","svd_calculation","svd_correspondence","svd_vs_diagonalization","symmetric_orthogonal_diagonalization","multivariate_normal_linear_algebra", ...
    "quadratic_form","diagonalization_components","diagonalization_calculation","diagonalization_representation","inverse_component_extraction","inverse_strategy","matrix_inner_product","matrix_product_composition","matrix_intro","quantification_iv_math","quantification_iv_application","weitzenbock_inequality"];
lessons=repmat(struct("video_id","","topic","","public_url",""),numel(ids),1);
for k=1:numel(ids), lessons(k)=struct("video_id",ids(k),"topic",topics(k),"public_url","https://www.youtube.com/watch?v="+ids(k)); end
report=struct("schema","matlab-acoustic-fembem.spectral-linear-algebra.v1","lessons",lessons, ...
    "seed",seed,"units",struct("matrix","1","sample","Pa"),"svd_reconstruction_error",reconstruct, ...
    "component_error",componentError,"isometry_error",max([isometryU isometryV]), ...
    "diagonalization_error",diagonalError,"whitening_error",whiteError, ...
    "spectral_candidate_is_ground_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
function ok=weitzenbockCheck()
a=3; b=4; c=5; sem=(a+b+c)/2; area=sqrt(sem*(sem-a)*(sem-b)*(sem-c)); ok=a^2+b^2+c^2>=4*sqrt(3)*area-1e-12;
end
