function report = vae_field_gate(seed)
%VAE_FIELD_GATE Readable linear VAE contract for CAE field snapshots.
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 47
end
rng(seed,"twister"); n=360; nf=6; nz=2;
wTrue=[1 .2;-.4 .8;.7 -.5;.1 .9;-.6 -.2;.5 .5];
zTrue=randn(n,nz); x=zTrue*wTrue'+.06*randn(n,nf); xMean=mean(x,1); xc=x-xMean;
[~,~,v]=svd(xc,"econ"); decoder=v(:,1:nz); mu=xc*decoder;
posteriorVar=.02; logvar=log(posteriorVar); epsilon=randn(size(mu));
z=mu+sqrt(posteriorVar)*epsilon; reconstruction=z*decoder'+xMean;
reconMse=mean((reconstruction-x).^2,"all"); baselineMse=mean((x-xMean).^2,"all");
klRows=.5*sum(mu.^2+posteriorVar-logvar-1,2); klMean=mean(klRows);
elboLoss=reconMse+klMean/nf;

% Reparameterization-path gradient check for one encoder mean coordinate.
analytic=2*(reconstruction(1,:)-x(1,:))*decoder(:,1)/(n*nf);
h=1e-6; muPlus=mu; muMinus=mu; muPlus(1,1)=muPlus(1,1)+h; muMinus(1,1)=muMinus(1,1)-h;
fd=(sampleLoss(muPlus,epsilon,posteriorVar,decoder,xMean,x)- ...
    sampleLoss(muMinus,epsilon,posteriorVar,decoder,xMean,x))/(2*h);
gradientError=abs(analytic-fd)/max(abs(analytic),1e-12);

qoiWeights=[1;-.5;.25;.1;.4;-.2]; y=x*qoiWeights; yRecon=reconstruction*qoiWeights;
yMean=repmat(xMean*qoiWeights,n,1);
solverRel=norm(yRecon-y)/norm(y); baselineRel=norm(yMean-y)/norm(y);

prior=[randn(63,nz);6 6]; generated=prior*decoder'+xMean;
latentRadius=sum(prior.^2,2); accepted=latentRadius<=9.21; % chi2(2), ~0.99
candidateQoi=generated*qoiWeights;
checks=struct("reconstruction_beats_mean",reconMse<baselineMse, ...
    "kl_nonnegative",all(klRows>=-1e-12),"elbo_finite",isfinite(elboLoss), ...
    "reparameterization_gradient",gradientError<1e-6, ...
    "forward_qoi_improves",solverRel<baselineRel, ...
    "ood_negative_control",any(~accepted)&&any(accepted), ...
    "generated_qoi_finite",all(isfinite(candidateQoi)));

report=struct("schema","matlab-acoustic-fembem.vae-field-gate.v1", ...
    "lesson",struct("video_id","wqmSkzDVKUE","public_url", ...
    "https://www.youtube.com/watch?v=wqmSkzDVKUE","principle", ...
    "variational free energy, KL term, and reparameterization"), ...
    "seed",seed,"units",struct("field","Pa","qoi","Pa"), ...
    "latent_dimension",nz,"reconstruction_mse",reconMse, ...
    "mean_baseline_mse",baselineMse,"kl_mean",klMean,"elbo_loss",elboLoss, ...
    "reparameterization_gradient_error",gradientError, ...
    "forward_qoi_relative_error",solverRel,"baseline_qoi_relative_error",baselineRel, ...
    "candidate_count",size(generated,1),"accepted_count",sum(accepted), ...
    "generated_candidate_is_ground_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
function loss=sampleLoss(mu,epsv,varv,decoder,xMean,x)
z=mu+sqrt(varv)*epsv; r=z*decoder'+xMean; loss=mean((r-x).^2,"all");
end
