function report = variational_geometry_gate(seed)
%VARIATIONAL_GEOMETRY_GATE KL/ELBO identities and geometry preservation.
arguments
    seed (1,1) double {mustBeInteger,mustBeNonnegative} = 71
end
rng(seed,"twister"); prior=[.55 .45]; likelihood=[.8 .25]; evidence=sum(prior.*likelihood);
posterior=prior.*likelihood/evidence; q=[.65 .35];
kl=sum(q.*log(q./posterior)); klEqual=sum(posterior.*log(posterior./posterior));
elbo=sum(q.*(log(prior)+log(likelihood)-log(q))); freeEnergy=-elbo;
identityError=abs(log(evidence)-(elbo+kl));
fiveForms=[freeEnergy,kl-log(evidence),-sum(q.*log(prior.*likelihood./q)), ...
    -elbo,sum(q.*log(q./posterior))-log(evidence)];

ang=.37; m=[cos(ang) sin(ang);-sin(ang) cos(ang)]; j=[0 1;-1 0];
symplecticError=norm(m'*j*m-j,"fro"); volumeError=abs(det(m)-1);
bad=[2 0;0 1]; badError=norm(bad'*j*bad-j,"fro");

% Smooth coordinate map and inverse on a positive-radius design chart.
x=[1.2;.4]; polar=[hypot(x(1),x(2));atan2(x(2),x(1))]; xr=polar(1)*[cos(polar(2));sin(polar(2))];
chartRoundtrip=norm(xr-x);
checks=struct("kl_nonnegative",kl>=0,"kl_zero_on_equal",abs(klEqual)<1e-12, ...
    "elbo_identity",identityError<1e-12,"five_forms_equal",max(abs(fiveForms-fiveForms(1)))<1e-12, ...
    "symplectic_preserved",symplecticError<1e-12,"volume_preserved",volumeError<1e-12, ...
    "nonsymplectic_negative_rejected",badError>1e-2,"chart_roundtrip",chartRoundtrip<1e-12);
report=struct("schema","matlab-acoustic-fembem.variational-geometry.v1", ...
    "lessons",[struct("video_id","4VgjKYFi2BI","topic","five_variational_free_energy_forms","public_url","https://www.youtube.com/watch?v=4VgjKYFi2BI"); ...
    struct("video_id","shfTAx-x00c","topic","elbo","public_url","https://www.youtube.com/watch?v=shfTAx-x00c"); ...
    struct("video_id","y6Qs1cXLvB0","topic","kl_nonnegativity","public_url","https://www.youtube.com/watch?v=y6Qs1cXLvB0"); ...
    struct("video_id","TpFkU6hKU9k","topic","kl_divergence","public_url","https://www.youtube.com/watch?v=TpFkU6hKU9k"); ...
    struct("video_id","NrdP-4ZvPOY","topic","topology_differential_geometry","public_url","https://www.youtube.com/watch?v=NrdP-4ZvPOY"); ...
    struct("video_id","qGMcmusboVQ","topic","symplectic_geometry","public_url","https://www.youtube.com/watch?v=qGMcmusboVQ")], ...
    "seed",seed,"units",struct("probability","1","geometry","1"), ...
    "kl",kl,"log_evidence",log(evidence),"elbo",elbo,"free_energy",freeEnergy, ...
    "five_forms",fiveForms,"identity_error",identityError, ...
    "symplectic_error",symplecticError,"bad_map_error",badError,"chart_roundtrip_error",chartRoundtrip, ...
    "variational_candidate_is_ground_truth",false,"promotion_requires_forward_solver",true, ...
    "checks",checks,"ok",all(structfun(@logical,checks)));
end
