function report = adjointScalingManifest(rows, gradientTolerance, affineTolerance, minimumFinalRatio)
%ADJOINTSCALINGMANIFEST Gate reverse-mode cost, FD agreement, and direction.
arguments
    rows (:,1) struct
    gradientTolerance (1,1) double {mustBeNonnegative} = 1e-6
    affineTolerance (1,1) double {mustBeNonnegative} = 1e-10
    minimumFinalRatio (1,1) double {mustBeNonnegative} = 1.0
end
if numel(rows) < 2
    error("adjointScalingManifest:rows", "At least two design-variable counts are required.");
end
counts = [rows.designVariableCount];
solves = [rows.adjointSolves];
gradientErrors = [rows.gradientCheckRelativeError];
affineResiduals = [rows.forwardAffineResidual];
plusRatios = [rows.plusAscentObjectiveRatio];
minusRatios = [rows.minusAscentObjectiveRatio];
finalRatios = [rows.fiftyStepObjectiveRatio];
checks = struct( ...
    "designVariableCountsStrictlyIncrease", all(diff(counts) > 0), ...
    "oneAdjointSolveForEverySize", all(solves == 1), ...
    "gradientsMatchFiniteDifference", all(gradientErrors <= gradientTolerance), ...
    "forwardMapAffineResidualSmall", all(affineResiduals <= affineTolerance), ...
    "positiveDirectionRaisesObjective", all(plusRatios > 1), ...
    "negativeDirectionLowersObjective", all(minusRatios < 1), ...
    "iterativeAscentIsMonotone", all([rows.fiftyStepMonotone]), ...
    "iterativeAscentImprovesObjective", all(finalRatios > minimumFinalRatio));
report = struct( ...
    "schema", "matlab-acoustic-fembem.adjoint-scaling.v1", ...
    "ok", all(structfun(@logical, checks)), ...
    "checks", checks, ...
    "designVariableCounts", counts, ...
    "adjointSolves", solves, ...
    "maxGradientRelativeError", max(gradientErrors), ...
    "maxForwardAffineResidual", max(affineResiduals), ...
    "minimumPlusAscentRatio", min(plusRatios), ...
    "maximumMinusAscentRatio", max(minusRatios), ...
    "minimumFinalObjectiveRatio", min(finalRatios));
end
