function checks = femBemManifestChecks(report)
%FEMBEMMANIFESTCHECKS Validate a recorded FEM/BEM coupling manifest.
%
% femBemCouplingManifest RECORDS the coupling identity; this function
% VALIDATES the record.  It reads only the report, so every check names one
% contract line that the recorded manifest must satisfy: identity strings
% recorded, operator bundle consistent with the trace, expected values
% matched, trace matrix one-hot, row identities bound to the same nodes.

arguments
    report (1,1) struct
end

T = report.trace.trace_matrix;
traceNodeIds = report.boundaryNodeIds(:);
surfaceTriangles = report.trace.surface_triangles;
boundaryNumbers = report.boundaryNumbers(:);
boundaryNames = report.boundaryNames(:);

rowNonzeroCount = sum(abs(T) > 0, 2);
rowMax = zeros(size(T, 1), 1);
traceMatrixNodeIds = zeros(size(T, 1), 1);
for k = 1:size(T, 1)
    rowMax(k) = max(abs(T(k, :)));
    nonzero = find(abs(T(k, :)) > 0);
    if isscalar(nonzero)
        traceMatrixNodeIds(k) = nonzero;
    else
        traceMatrixNodeIds(k) = NaN;
    end
end

traceRowIndex = [report.traceRowIdentity.trace_row_index].';
traceRowFemNodeIds = [report.traceRowIdentity.fem_node_id].';
traceRowBemNodeIds = [report.traceRowIdentity.bem_node_id].';
operatorTraceRowIndex = [report.operatorTraceRowIdentity.trace_row_index].';
operatorTraceRowFemNodeIds = [report.operatorTraceRowIdentity.fem_node_id].';
operatorTraceRowBemNodeIds = [report.operatorTraceRowIdentity.bem_node_id].';
[boundaryRowIndices, boundaryRowTriangles, boundaryRowNumbers, boundaryRowNames] = ...
    boundaryRowIdentityArrays(report.boundaryRowIdentity);

checks = struct();

% --- mesh / trace artifact identity is recorded ---
checks.meshIdRecorded = strlength(report.meshId) > 0;
checks.surfaceMeshIdRecorded = strlength(report.surfaceMeshId) > 0;
checks.traceArtifactIdRecorded = strlength(report.traceArtifactId) > 0;
checks.traceOperatorArtifactIdRecorded = strlength(report.traceOperatorArtifactId) > 0;
checks.operatorTraceOperatorArtifactIdRecorded = strlength(report.operatorTraceOperatorArtifactId) > 0;
checks.operatorTraceOperatorArtifactIdMatchesTrace = ...
    report.operatorTraceOperatorArtifactId == report.traceOperatorArtifactId;
checks.traceOperatorPolicyRecorded = strlength(report.traceOperatorPolicy) > 0;
checks.operatorTraceOperatorPolicyRecorded = strlength(report.operatorTraceOperatorPolicy) > 0;
checks.operatorTraceOperatorPolicyMatchesTrace = ...
    report.operatorTraceOperatorPolicy == report.traceOperatorPolicy;
checks.traceOperatorPolicyMatchesExpected = ...
    report.traceOperatorPolicy == report.expectedTraceOperatorPolicy;
checks.traceOperatorArtifactIdMatchesExpected = ...
    strlength(report.expectedTraceOperatorArtifactId) == 0 || ...
    report.traceOperatorArtifactId == report.expectedTraceOperatorArtifactId;

% --- trace output artifact ---
checks.traceOutputArtifactIdRecordedWhenRequired = ...
    ~report.requireTraceOutputArtifact || strlength(report.traceOutputArtifactId) > 0;
checks.traceOutputDigestRecordedWhenRequired = ...
    ~report.requireTraceOutputArtifact || strlength(report.traceOutputDigest) > 0;
checks.traceOutputPathRecordedWhenRequired = ...
    ~report.requireTraceOutputArtifact || strlength(report.traceOutputPath) > 0;
checks.operatorTraceOutputArtifactIdMatchesTrace = ...
    report.operatorTraceOutputArtifactId == report.traceOutputArtifactId;
checks.operatorTraceOutputDigestMatchesTrace = ...
    report.operatorTraceOutputDigest == report.traceOutputDigest;
checks.operatorTraceOutputPathMatchesTrace = ...
    report.operatorTraceOutputPath == report.traceOutputPath;
checks.traceOutputArtifactIdMatchesExpected = ...
    strlength(report.expectedTraceOutputArtifactId) == 0 || ...
    report.traceOutputArtifactId == report.expectedTraceOutputArtifactId;
checks.traceOutputDigestMatchesExpected = ...
    strlength(report.expectedTraceOutputDigest) == 0 || ...
    report.traceOutputDigest == report.expectedTraceOutputDigest;

% --- trace observable identity ---
checks.traceObservableIdRecorded = strlength(report.traceObservableId) > 0;
checks.operatorTraceObservableIdRecorded = strlength(report.operatorTraceObservableId) > 0;
checks.operatorTraceObservableIdMatchesTrace = ...
    report.operatorTraceObservableId == report.traceObservableId;
checks.traceObservableIdMatchesExpected = ...
    strlength(report.expectedTraceObservableId) == 0 || ...
    report.traceObservableId == report.expectedTraceObservableId;
checks.traceObservableFamilyRecorded = strlength(report.traceObservableFamily) > 0;
checks.operatorTraceObservableFamilyRecorded = strlength(report.operatorTraceObservableFamily) > 0;
checks.operatorTraceObservableFamilyMatchesTrace = ...
    report.operatorTraceObservableFamily == report.traceObservableFamily;
checks.traceObservableFamilyMatchesExpected = ...
    report.traceObservableFamily == report.expectedTraceObservableFamily;

% --- normal flux artifact ---
checks.normalFluxConventionRecorded = strlength(report.normalFluxConvention) > 0;
checks.normalFluxConventionMatchesExpected = ...
    report.normalFluxConvention == report.expectedNormalFluxConvention;
checks.normalFluxArtifactIdRecordedWhenRequired = ...
    ~report.requireNormalFluxArtifact || strlength(report.normalFluxArtifactId) > 0;
checks.normalFluxDigestRecordedWhenRequired = ...
    ~report.requireNormalFluxArtifact || strlength(report.normalFluxDigest) > 0;
checks.normalFluxArtifactIdMatchesExpected = ...
    strlength(report.expectedNormalFluxArtifactId) == 0 || ...
    report.normalFluxArtifactId == report.expectedNormalFluxArtifactId;
checks.normalFluxDigestMatchesExpected = ...
    strlength(report.expectedNormalFluxDigest) == 0 || ...
    report.normalFluxDigest == report.expectedNormalFluxDigest;

% --- linear solver report ---
checks.linearSolverReportArtifactIdRecordedWhenRequired = ...
    ~report.requireLinearSolverReport || strlength(report.linearSolverReportArtifactId) > 0;
checks.linearSolverReportDigestRecordedWhenRequired = ...
    ~report.requireLinearSolverReport || strlength(report.linearSolverReportDigest) > 0;
checks.linearSolverNameRecordedWhenRequired = ...
    ~report.requireLinearSolverReport || strlength(report.linearSolverName) > 0;
checks.linearSolverToleranceRecordedWhenRequired = ...
    ~report.requireLinearSolverReport || ~isnan(report.linearSolverTolerance);
checks.linearSolverResidualNormRecordedWhenRequired = ...
    ~report.requireLinearSolverReport || ~isnan(report.linearSolverResidualNorm);
checks.linearSolverToleranceFinitePositiveWhenPresent = ...
    isnan(report.linearSolverTolerance) || ...
    (isfinite(report.linearSolverTolerance) && report.linearSolverTolerance > 0);
checks.linearSolverResidualNormFiniteNonnegativeWhenPresent = ...
    isnan(report.linearSolverResidualNorm) || ...
    (isfinite(report.linearSolverResidualNorm) && report.linearSolverResidualNorm >= 0);
checks.linearSolverIterationCountNonnegativeWhenPresent = ...
    isnan(report.linearSolverIterationCount) || ...
    (isfinite(report.linearSolverIterationCount) && report.linearSolverIterationCount >= 0 && ...
    report.linearSolverIterationCount == fix(report.linearSolverIterationCount));
checks.linearSolverReportArtifactIdMatchesExpected = ...
    strlength(report.expectedLinearSolverReportArtifactId) == 0 || ...
    report.linearSolverReportArtifactId == report.expectedLinearSolverReportArtifactId;
checks.linearSolverReportDigestMatchesExpected = ...
    strlength(report.expectedLinearSolverReportDigest) == 0 || ...
    report.linearSolverReportDigest == report.expectedLinearSolverReportDigest;
checks.linearSolverNameMatchesExpected = ...
    strlength(report.expectedLinearSolverName) == 0 || ...
    report.linearSolverName == report.expectedLinearSolverName;
checks.linearSolverToleranceMatchesExpected = ...
    isnan(report.expectedLinearSolverTolerance) || ...
    (~isnan(report.linearSolverTolerance) && ...
    abs(report.linearSolverTolerance - report.expectedLinearSolverTolerance) <= ...
    max(1e-14, abs(report.expectedLinearSolverTolerance) * 1e-12));
checks.linearSolverResidualNormBelowExpectedMax = ...
    isnan(report.expectedLinearSolverResidualNormMax) || ...
    (~isnan(report.linearSolverResidualNorm) && ...
    report.linearSolverResidualNorm <= report.expectedLinearSolverResidualNormMax);

% --- result package / execution pedigree ---
checks.resultArtifactIdRecorded = strlength(report.resultArtifactId) > 0;
checks.resultArtifactIdMatchesExpected = ...
    report.resultArtifactId == report.expectedResultArtifactId;
checks.runStartedAtRecorded = strlength(report.runStartedAt) > 0;
checks.runStartedAtIsoLike = isIsoTimestamp(report.runStartedAt);
checks.matlabVersionRecorded = strlength(report.matlabVersion) > 0;
checks.matlabVersionMatchesExpected = ...
    strlength(report.expectedMatlabVersion) == 0 || ...
    report.matlabVersion == report.expectedMatlabVersion;
checks.notebookSourceArtifactIdRecordedWhenRequired = ...
    ~report.requireNotebookSourceArtifact || strlength(report.notebookSourceArtifactId) > 0;
checks.notebookSourceDigestRecordedWhenRequired = ...
    ~report.requireNotebookSourceArtifact || strlength(report.notebookSourceDigest) > 0;
checks.notebookSourcePathRecordedWhenRequired = ...
    ~report.requireNotebookSourceArtifact || strlength(report.notebookSourcePath) > 0;
checks.notebookSourceArtifactIdMatchesExpected = ...
    strlength(report.expectedNotebookSourceArtifactId) == 0 || ...
    report.notebookSourceArtifactId == report.expectedNotebookSourceArtifactId;
checks.notebookSourceDigestMatchesExpected = ...
    strlength(report.expectedNotebookSourceDigest) == 0 || ...
    report.notebookSourceDigest == report.expectedNotebookSourceDigest;
checks.notebookSourcePathMatchesExpected = ...
    strlength(report.expectedNotebookSourcePath) == 0 || ...
    report.notebookSourcePath == report.expectedNotebookSourcePath;
checks.parameterSetArtifactIdRecordedWhenRequired = ...
    ~report.requireParameterSetArtifact || strlength(report.parameterSetArtifactId) > 0;
checks.parameterSetDigestRecordedWhenRequired = ...
    ~report.requireParameterSetArtifact || strlength(report.parameterSetDigest) > 0;
checks.parameterSetPathRecordedWhenRequired = ...
    ~report.requireParameterSetArtifact || strlength(report.parameterSetPath) > 0;
checks.parameterSetArtifactIdMatchesExpected = ...
    strlength(report.expectedParameterSetArtifactId) == 0 || ...
    report.parameterSetArtifactId == report.expectedParameterSetArtifactId;
checks.parameterSetDigestMatchesExpected = ...
    strlength(report.expectedParameterSetDigest) == 0 || ...
    report.parameterSetDigest == report.expectedParameterSetDigest;
checks.parameterSetPathMatchesExpected = ...
    strlength(report.expectedParameterSetPath) == 0 || ...
    report.parameterSetPath == report.expectedParameterSetPath;
checks.objectiveObservableIdMatchesExpected = ...
    strlength(report.expectedObjectiveObservableId) == 0 || ...
    report.objectiveObservableId == report.expectedObjectiveObservableId;
checks.objectiveObservableFamilyMatchesExpected = ...
    strlength(report.expectedObjectiveObservableFamily) == 0 || ...
    report.objectiveObservableFamily == report.expectedObjectiveObservableFamily;
checks.timingBreakdownRecorded = numel(report.timingBreakdownNames) > 0;
checks.timingBreakdownHasFourItems = numel(report.timingBreakdownNames) >= 4;
checks.timingBreakdownHasAtMostFourItems = numel(report.timingBreakdownNames) <= 4;
checks.timingBreakdownFiniteNonnegative = ...
    all(isfinite(report.timingBreakdownSeconds)) && ...
    all(report.timingBreakdownSeconds >= 0);

% --- .vol source identity travels with the trace ---
checks.sourceFileIdRecorded = strlength(report.sourceFileId) > 0;
checks.traceSourceFileIdRecorded = strlength(string(report.trace.source_file_id)) > 0;
checks.traceSourceFileIdMatchesIdentity = string(report.trace.source_file_id) == report.sourceFileId;
checks.operatorTraceSourceFileIdRecorded = strlength(report.operatorTraceSourceFileId) > 0;
checks.operatorTraceSourceFileIdMatchesIdentity = report.operatorTraceSourceFileId == report.sourceFileId;

% --- boundary-condition identity ---
checks.boundaryNumbersRecorded = numel(boundaryNumbers) == size(surfaceTriangles, 1);
checks.boundaryNamesRecorded = numel(boundaryNames) == size(surfaceTriangles, 1) && all(strlength(boundaryNames) > 0);
checks.boundaryRowIdentityRecorded = numel(report.boundaryRowIdentity) == size(surfaceTriangles, 1);
checks.boundaryRowIdentityRowIndicesMatch = isequal(boundaryRowIndices, (1:size(surfaceTriangles, 1)).');
checks.boundaryRowIdentityTrianglesMatch = isequal(boundaryRowTriangles, surfaceTriangles);
checks.boundaryRowIdentityNumbersMatch = isequal(boundaryRowNumbers(:), boundaryNumbers(:));
checks.boundaryRowIdentityNamesMatch = isequal(boundaryRowNames(:), boundaryNames(:));
checks.boundaryNumbersMatchExpected = isempty(report.expectedBoundaryNumbers) || ...
    isequal(sort(unique(boundaryNumbers(:))), report.expectedBoundaryNumbers);
checks.boundaryNamesMatchExpected = isempty(report.expectedBoundaryNames) || ...
    isequal(sort(unique(boundaryNames(:))), report.expectedBoundaryNames);

% --- coupling schema / kernel / spaces ---
checks.sourceFormatIsVol = report.sourceFormat == ".vol";
checks.volumeSpaceMatchesExpected = report.volumeSpace == report.expectedVolumeSpace;
checks.surfaceSpaceMatchesExpected = report.surfaceSpace == report.expectedSurfaceSpace;
checks.couplingKindMatchesExpected = report.couplingKind == report.expectedCouplingKind;
checks.formulationIdMatchesExpected = report.formulationId == report.expectedFormulationId;
checks.bemKernelFamilyMatchesExpected = report.bemKernelFamily == report.expectedBemKernelFamily;
checks.couplingConventionSchemaIdRecordedWhenRequired = ...
    ~report.requireCouplingConventionSchema || strlength(report.couplingConventionSchemaId) > 0;
checks.couplingConventionSchemaIdMatchesExpected = ...
    strlength(report.expectedCouplingConventionSchemaId) == 0 || ...
    report.couplingConventionSchemaId == report.expectedCouplingConventionSchemaId;
checks.postprocessRowConventionSchemaIdRecordedWhenRequired = ...
    ~report.requirePostprocessRowConventionSchema || strlength(report.postprocessRowConventionSchemaId) > 0;
checks.postprocessRowConventionSchemaIdMatchesExpected = ...
    strlength(report.expectedPostprocessRowConventionSchemaId) == 0 || ...
    report.postprocessRowConventionSchemaId == report.expectedPostprocessRowConventionSchemaId;
checks.traceBasisSchemaIdRecordedWhenRequired = ...
    ~report.requireTraceBasisSchema || strlength(report.traceBasisSchemaId) > 0;
checks.traceBasisSchemaIdMatchesExpected = ...
    strlength(report.expectedTraceBasisSchemaId) == 0 || ...
    report.traceBasisSchemaId == report.expectedTraceBasisSchemaId;
checks.operatorTraceBasisSchemaIdRecorded = strlength(report.operatorTraceBasisSchemaId) > 0;
checks.operatorTraceBasisSchemaIdMatchesTrace = ...
    report.operatorTraceBasisSchemaId == report.traceBasisSchemaId;
checks.bemKernelManifestIdRecorded = strlength(report.bemKernelManifestId) > 0;
checks.bemKernelManifestIdMatchesExpected = ...
    report.bemKernelManifestId == report.expectedBemKernelManifestId;
checks.bemKernelStrategyRecorded = strlength(report.bemKernelStrategy) > 0;
checks.bemKernelStrategyMatchesExpected = ...
    report.bemKernelStrategy == report.expectedBemKernelStrategy;
checks.kernelTimeConventionRecorded = strlength(report.kernelTimeConvention) > 0;
checks.kernelTimeConventionMatchesExpected = ...
    report.kernelTimeConvention == report.expectedKernelTimeConvention;
checks.assemblyRuleIdRecorded = strlength(report.assemblyRuleId) > 0;
checks.operatorTraceAssemblyRuleIdRecorded = strlength(report.operatorTraceAssemblyRuleId) > 0;
checks.operatorTraceAssemblyRuleIdMatchesTrace = ...
    report.operatorTraceAssemblyRuleId == report.assemblyRuleId;
checks.assemblyRuleIdMatchesExpected = ...
    report.assemblyRuleId == report.expectedAssemblyRuleId;
checks.quadratureRuleIdRecorded = strlength(report.quadratureRuleId) > 0;
checks.operatorTraceQuadratureRuleIdRecorded = strlength(report.operatorTraceQuadratureRuleId) > 0;
checks.operatorTraceQuadratureRuleIdMatchesTrace = ...
    report.operatorTraceQuadratureRuleId == report.quadratureRuleId;
checks.quadratureRuleIdMatchesExpected = ...
    report.quadratureRuleId == report.expectedQuadratureRuleId;

% --- trace matrix structure and row identity ---
checks.traceRowsMatchBoundaryNodes = size(T, 1) == numel(traceNodeIds);
checks.traceColumnsMatchVolumeNodes = size(T, 2) == report.geo.N;
checks.traceRowsAreOneHot = all(rowNonzeroCount == 1) && all(abs(rowMax - 1) < 1e-14);
checks.traceRowIdentityRecorded = numel(report.traceRowIdentity) == numel(traceNodeIds);
checks.traceRowIdentityRowIndicesMatch = isequal(traceRowIndex, (1:numel(traceNodeIds)).');
checks.traceRowIdentityFemNodesMatch = isequal(traceRowFemNodeIds, traceNodeIds);
checks.traceRowIdentityBemNodesMatch = isequal(traceRowBemNodeIds, traceNodeIds);
checks.traceRowIdentityUnique = ...
    numel(unique(traceRowFemNodeIds)) == numel(traceRowFemNodeIds) && ...
    numel(unique(traceRowBemNodeIds)) == numel(traceRowBemNodeIds);
checks.traceRowIdentityMatchesTraceMatrix = isequal(traceRowFemNodeIds, traceMatrixNodeIds);
checks.operatorTraceRowIdentityRecorded = numel(report.operatorTraceRowIdentity) == numel(traceNodeIds);
checks.operatorTraceRowIdentityMatchesTrace = isequal(report.operatorTraceRowIdentity, report.traceRowIdentity);
checks.operatorTraceRowIdentityRowIndicesMatch = isequal(operatorTraceRowIndex, (1:numel(traceNodeIds)).');
checks.operatorTraceRowIdentityFemNodesMatch = isequal(operatorTraceRowFemNodeIds, traceNodeIds);
checks.operatorTraceRowIdentityBemNodesMatch = isequal(operatorTraceRowBemNodeIds, traceNodeIds);
checks.operatorTraceRowIdentityMatchesTraceMatrix = isequal(operatorTraceRowFemNodeIds, traceMatrixNodeIds);
end


function tf = isIsoTimestamp(value)
text = char(string(value));
tf = ~isempty(regexp(text, ...
    '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(Z|[+-]\d{2}:\d{2})?$', ...
    'once'));
end


function [indices, triangles, numbers, names] = boundaryRowIdentityArrays(identity)
nRows = numel(identity);
indices = zeros(nRows, 1);
triangles = zeros(nRows, 3);
numbers = zeros(nRows, 1);
names = strings(nRows, 1);
for k = 1:nRows
    indices(k) = identity(k).surface_triangle_index;
    triangles(k, :) = identity(k).surface_triangle_nodes;
    numbers(k) = identity(k).boundary_number;
    names(k) = string(identity(k).boundary_name);
end
end
