function profile = balancedLearningProfile()
%BALANCEDLEARNINGPROFILE Return the ten-stage equal MCP learning contract.

ids = [ ...
    "baseline_gap", "source_controls", "structured_output", ...
    "input_validation", "security_boundary", "timeout_cancel_progress", ...
    "source_provenance", "artifact_feedback", "protocol_smoke", ...
    "balance_audit"];
objectives = [ ...
    "Prove the pre-change capability gap.", ...
    "Bind source-native positive and negative controls.", ...
    "Publish a stable structured result contract.", ...
    "Validate required inputs at the MCP boundary.", ...
    "Keep path, provenance, and execution boundaries explicit.", ...
    "Bound long work and expose progress/cancel semantics.", ...
    "Tie learning to a source-native artifact and version.", ...
    "Feed verified result artifacts back into MCP behavior.", ...
    "Exercise the actual MCP protocol surface.", ...
    "Require equal public and source capability gains."];

stages = repmat(struct( ...
    "round", 0, "capability_id", "", "objective", "", ...
    "positive_control", "", "negative_control", ""), 1, numel(ids));
for index = 1:numel(ids)
    stages(index) = struct( ...
        "round", index, ...
        "capability_id", ids(index), ...
        "objective", objectives(index), ...
        "positive_control", "Complete source-native evidence is accepted.", ...
        "negative_control", "Incomplete or one-sided evidence is rejected.");
end

profile = struct( ...
    "schema", "cae-" + "ai-lab.balanced-mcp-learning-profile.v1", ...
    "policy", "equal_capability_gain_v1", ...
    "server", "matlab-acoustic-fembem", ...
    "public_owner", "radia-mcp", ...
    "source_owner", "matlab-acoustic-fembem", ...
    "stage_count", numel(stages), ...
    "stages", stages, ...
    "workflow_roles", struct( ...
        "detect", "Observe baseline and MATLAB/runtime availability.", ...
        "check", "Run typed positive and negative controls.", ...
        "run", "Use the existing shared MATLAB session when applicable.", ...
        "test", "Run MATLAB tests, protocol probe, artifact gate, and commit evidence."), ...
    "protocol_policy", struct( ...
        "inspector_cli", "Prefer tools/list plus tools/call through MCP Inspector CLI.", ...
        "conformance", "Rotate official MCP conformance scenarios across a full loop.", ...
        "fallback", "Record why a direct MATLAB MCP probe was used."), ...
    "completion_rule", "Both public and source lanes need behavior, controls, tests, and non-pending commits.");
profile.self_check = validateBalancedLearningProfile(profile);
end
