function report = cqResponseRealityManifest(summary, residualTolerance, imaginaryTolerance)
%CQRESPONSEREALITYMANIFEST Gate a coupled CQ run and real reconstruction.
arguments
    summary (1,1) struct
    residualTolerance (1,1) double = 1e-10
    imaginaryTolerance (1,1) double = 1e-10
end
method = upper(string(summary.method));
coupling = string(summary.coupling_form);
checks = struct( ...
    "methodSupported", any(method == ["BDF1", "BDF2"]), ...
    "oneLaplaceSolvePerCqNode", summary.num_time_steps >= 2 && summary.num_laplace_solves == summary.num_time_steps, ...
    "laplaceNodesRightHalfPlane", summary.min_real_laplace_parameter > 0, ...
    "coupledResidualSmall", summary.max_relative_residual <= residualTolerance, ...
    "interiorResponseReal", summary.interior_imag_relative <= imaginaryTolerance, ...
    "exteriorResponseReal", summary.exterior_imag_relative <= imaginaryTolerance, ...
    "calderonDoubleLayerPresent", coupling ~= "JohnsonNedelec" || summary.double_layer_included);
report = struct("schema", "matlab-acoustic-fembem.cq-response-reality.v1", ...
    "ok", all(structfun(@logical, checks)), "method", method, ...
    "couplingForm", coupling, "checks", checks, ...
    "residualTolerance", residualTolerance, "imaginaryTolerance", imaginaryTolerance);
end
