function report = cqTimeGridManifest(dt, nSteps, method, contourSamples, radius)
%CQTIMEGRIDMANIFEST Validate a readable Lubich CQ time-grid contract.

arguments
    dt (1,1) double
    nSteps (1,1) double
    method (1,1) string = "BDF2"
    contourSamples (1,1) double = 0
    radius (1,1) double = 0
end

method = upper(method);
if contourSamples == 0
    contourSamples = 2^nextpow2(2*nSteps);
end
if radius == 0 && contourSamples > 0
    radius = eps^(0.5/contourSamples);
end

validMethod = any(method == ["BDF1", "BDF2"]);
validShape = isfinite(dt) && dt > 0 && isfinite(nSteps) && nSteps >= 2 ...
    && fix(nSteps) == nSteps && isfinite(contourSamples) ...
    && contourSamples >= nSteps && fix(contourSamples) == contourSamples ...
    && isfinite(radius) && radius > 0 && radius < 1;

minRealLaplaceNode = NaN;
if validMethod && validShape
    j = (0:contourSamples-1).';
    zeta = radius * exp(-2i*pi*j/contourSamples);
    s = bdfDelta(zeta, method) / dt;
    minRealLaplaceNode = min(real(s));
end

checks = struct( ...
    "methodSupported", validMethod, ...
    "timeStepPositive", isfinite(dt) && dt > 0, ...
    "stepCountValid", isfinite(nSteps) && nSteps >= 2 && fix(nSteps) == nSteps, ...
    "contourCoversTimeGrid", isfinite(contourSamples) && contourSamples >= nSteps ...
        && fix(contourSamples) == contourSamples, ...
    "radiusInsideUnitCircle", isfinite(radius) && radius > 0 && radius < 1, ...
    "laplaceNodesInRightHalfPlane", isfinite(minRealLaplaceNode) ...
        && minRealLaplaceNode > 0);

report = struct( ...
    "schema", "matlab-acoustic-fembem.cq-time-grid.v1", ...
    "ok", all(structfun(@(value) logical(value), checks)), ...
    "method", method, ...
    "timeStep", dt, ...
    "numTimeSteps", nSteps, ...
    "contourSamples", contourSamples, ...
    "radius", radius, ...
    "timeEnd", (nSteps - 1) * dt, ...
    "minRealLaplaceNode", minRealLaplaceNode, ...
    "checks", checks, ...
    "notes", [ ...
        "M>=N is the shared contract; M=N and padded power-of-two FFTs are both valid." ...
        "BDF1/BDF2 CQ maps the rho-circle to Re(s)>0 for decaying Laplace kernels." ...
    ]);
end
