function report = validateBalancedLearningProfile(profile)
%VALIDATEBALANCEDLEARNINGPROFILE Self-check the ten-stage MCP profile.

expected = [ ...
    "baseline_gap", "source_controls", "structured_output", ...
    "input_validation", "security_boundary", "timeout_cancel_progress", ...
    "source_provenance", "artifact_feedback", "protocol_smoke", ...
    "balance_audit"];
ids = [profile.stages.capability_id];
rounds = [profile.stages.round];
positive = [profile.stages.positive_control];
negative = [profile.stages.negative_control];
roleNames = sort(string(fieldnames(profile.workflow_roles)));
protocolNames = sort(string(fieldnames(profile.protocol_policy)));
checks = struct( ...
    "stage_ids_match", isequal(ids, expected), ...
    "rounds_ordered", isequal(rounds, 1:10), ...
    "controls_complete", numel(ids) == 10 && all(strlength(positive) > 0) ...
        && all(strlength(negative) > 0), ...
    "workflow_roles_complete", isequal(roleNames, sort(["detect"; "check"; "run"; "test"])), ...
    "protocol_policy_complete", isequal(protocolNames, sort(["conformance"; "fallback"; "inspector_cli"])));
ok = all(structfun(@(value) logical(value), checks));
status = "needs_attention";
if ok
    status = "ok";
end
checkNames = string(fieldnames(checks)).';
checkValues = structfun(@(value) logical(value), checks).';
report = struct( ...
    "status", status, ...
    "checks", checks, ...
    "issues", checkNames(~checkValues));
end
